convert ./bmp/sprite_001_front.bmp	./xpm/sprite_001_front.xpm 2>/dev/null
convert ./bmp/sprite_001_back.bmp	./xpm/sprite_001_back.xpm 2>/dev/null
convert ./bmp/sprite_002_front.bmp	./xpm/sprite_002_front.xpm 2>/dev/null
convert ./bmp/sprite_002_back.bmp	./xpm/sprite_002_back.xpm 2>/dev/null
convert ./bmp/sprite_003_front.bmp	./xpm/sprite_003_front.xpm 2>/dev/null
convert ./bmp/sprite_003_back.bmp	./xpm/sprite_003_back.xpm 2>/dev/null
convert ./bmp/sprite_004_front.bmp	./xpm/sprite_004_front.xpm 2>/dev/null
convert ./bmp/sprite_004_back.bmp	./xpm/sprite_004_back.xpm 2>/dev/null
convert ./bmp/sprite_005_front.bmp	./xpm/sprite_005_front.xpm 2>/dev/null
convert ./bmp/sprite_005_back.bmp	./xpm/sprite_005_back.xpm 2>/dev/null
convert ./bmp/sprite_006_front.bmp	./xpm/sprite_006_front.xpm 2>/dev/null
convert ./bmp/sprite_006_back.bmp	./xpm/sprite_006_back.xpm 2>/dev/null
convert ./bmp/sprite_007_front.bmp	./xpm/sprite_007_front.xpm 2>/dev/null
convert ./bmp/sprite_007_back.bmp	./xpm/sprite_007_back.xpm 2>/dev/null
convert ./bmp/sprite_008_front.bmp	./xpm/sprite_008_front.xpm 2>/dev/null
convert ./bmp/sprite_008_back.bmp	./xpm/sprite_008_back.xpm 2>/dev/null
convert ./bmp/sprite_009_front.bmp	./xpm/sprite_009_front.xpm 2>/dev/null
convert ./bmp/sprite_009_back.bmp	./xpm/sprite_009_back.xpm 2>/dev/null
convert ./bmp/sprite_010_front.bmp	./xpm/sprite_010_front.xpm 2>/dev/null
convert ./bmp/sprite_010_back.bmp	./xpm/sprite_010_back.xpm 2>/dev/null
convert ./bmp/sprite_011_front.bmp	./xpm/sprite_011_front.xpm 2>/dev/null
convert ./bmp/sprite_011_back.bmp	./xpm/sprite_011_back.xpm 2>/dev/null
convert ./bmp/sprite_012_front.bmp	./xpm/sprite_012_front.xpm 2>/dev/null
convert ./bmp/sprite_012_back.bmp	./xpm/sprite_012_back.xpm 2>/dev/null
convert ./bmp/sprite_013_front.bmp	./xpm/sprite_013_front.xpm 2>/dev/null
convert ./bmp/sprite_013_back.bmp	./xpm/sprite_013_back.xpm 2>/dev/null
convert ./bmp/sprite_014_front.bmp	./xpm/sprite_014_front.xpm 2>/dev/null
convert ./bmp/sprite_014_back.bmp	./xpm/sprite_014_back.xpm 2>/dev/null
convert ./bmp/sprite_015_front.bmp	./xpm/sprite_015_front.xpm 2>/dev/null
convert ./bmp/sprite_015_back.bmp	./xpm/sprite_015_back.xpm 2>/dev/null
convert ./bmp/sprite_016_front.bmp	./xpm/sprite_016_front.xpm 2>/dev/null
convert ./bmp/sprite_016_back.bmp	./xpm/sprite_016_back.xpm 2>/dev/null
convert ./bmp/sprite_017_front.bmp	./xpm/sprite_017_front.xpm 2>/dev/null
convert ./bmp/sprite_017_back.bmp	./xpm/sprite_017_back.xpm 2>/dev/null
convert ./bmp/sprite_018_front.bmp	./xpm/sprite_018_front.xpm 2>/dev/null
convert ./bmp/sprite_018_back.bmp	./xpm/sprite_018_back.xpm 2>/dev/null
convert ./bmp/sprite_019_front.bmp	./xpm/sprite_019_front.xpm 2>/dev/null
convert ./bmp/sprite_019_back.bmp	./xpm/sprite_019_back.xpm 2>/dev/null
convert ./bmp/sprite_020_front.bmp	./xpm/sprite_020_front.xpm 2>/dev/null
convert ./bmp/sprite_020_back.bmp	./xpm/sprite_020_back.xpm 2>/dev/null
convert ./bmp/sprite_021_front.bmp	./xpm/sprite_021_front.xpm 2>/dev/null
convert ./bmp/sprite_021_back.bmp	./xpm/sprite_021_back.xpm 2>/dev/null
convert ./bmp/sprite_022_front.bmp	./xpm/sprite_022_front.xpm 2>/dev/null
convert ./bmp/sprite_022_back.bmp	./xpm/sprite_022_back.xpm 2>/dev/null
convert ./bmp/sprite_023_front.bmp	./xpm/sprite_023_front.xpm 2>/dev/null
convert ./bmp/sprite_023_back.bmp	./xpm/sprite_023_back.xpm 2>/dev/null
convert ./bmp/sprite_024_front.bmp	./xpm/sprite_024_front.xpm 2>/dev/null
convert ./bmp/sprite_024_back.bmp	./xpm/sprite_024_back.xpm 2>/dev/null
convert ./bmp/sprite_025_front.bmp	./xpm/sprite_025_front.xpm 2>/dev/null
convert ./bmp/sprite_025_back.bmp	./xpm/sprite_025_back.xpm 2>/dev/null
convert ./bmp/sprite_026_front.bmp	./xpm/sprite_026_front.xpm 2>/dev/null
convert ./bmp/sprite_026_back.bmp	./xpm/sprite_026_back.xpm 2>/dev/null
convert ./bmp/sprite_027_front.bmp	./xpm/sprite_027_front.xpm 2>/dev/null
convert ./bmp/sprite_027_back.bmp	./xpm/sprite_027_back.xpm 2>/dev/null
convert ./bmp/sprite_028_front.bmp	./xpm/sprite_028_front.xpm 2>/dev/null
convert ./bmp/sprite_028_back.bmp	./xpm/sprite_028_back.xpm 2>/dev/null
convert ./bmp/sprite_029_front.bmp	./xpm/sprite_029_front.xpm 2>/dev/null
convert ./bmp/sprite_029_back.bmp	./xpm/sprite_029_back.xpm 2>/dev/null
convert ./bmp/sprite_030_front.bmp	./xpm/sprite_030_front.xpm 2>/dev/null
convert ./bmp/sprite_030_back.bmp	./xpm/sprite_030_back.xpm 2>/dev/null
convert ./bmp/sprite_031_front.bmp	./xpm/sprite_031_front.xpm 2>/dev/null
convert ./bmp/sprite_031_back.bmp	./xpm/sprite_031_back.xpm 2>/dev/null
convert ./bmp/sprite_032_front.bmp	./xpm/sprite_032_front.xpm 2>/dev/null
convert ./bmp/sprite_032_back.bmp	./xpm/sprite_032_back.xpm 2>/dev/null
convert ./bmp/sprite_033_front.bmp	./xpm/sprite_033_front.xpm 2>/dev/null
convert ./bmp/sprite_033_back.bmp	./xpm/sprite_033_back.xpm 2>/dev/null
convert ./bmp/sprite_034_front.bmp	./xpm/sprite_034_front.xpm 2>/dev/null
convert ./bmp/sprite_034_back.bmp	./xpm/sprite_034_back.xpm 2>/dev/null
convert ./bmp/sprite_035_front.bmp	./xpm/sprite_035_front.xpm 2>/dev/null
convert ./bmp/sprite_035_back.bmp	./xpm/sprite_035_back.xpm 2>/dev/null
convert ./bmp/sprite_036_front.bmp	./xpm/sprite_036_front.xpm 2>/dev/null
convert ./bmp/sprite_036_back.bmp	./xpm/sprite_036_back.xpm 2>/dev/null
convert ./bmp/sprite_037_front.bmp	./xpm/sprite_037_front.xpm 2>/dev/null
convert ./bmp/sprite_037_back.bmp	./xpm/sprite_037_back.xpm 2>/dev/null
convert ./bmp/sprite_038_front.bmp	./xpm/sprite_038_front.xpm 2>/dev/null
convert ./bmp/sprite_038_back.bmp	./xpm/sprite_038_back.xpm 2>/dev/null
convert ./bmp/sprite_039_front.bmp	./xpm/sprite_039_front.xpm 2>/dev/null
convert ./bmp/sprite_039_back.bmp	./xpm/sprite_039_back.xpm 2>/dev/null
convert ./bmp/sprite_040_front.bmp	./xpm/sprite_040_front.xpm 2>/dev/null
convert ./bmp/sprite_040_back.bmp	./xpm/sprite_040_back.xpm 2>/dev/null
convert ./bmp/sprite_041_front.bmp	./xpm/sprite_041_front.xpm 2>/dev/null
convert ./bmp/sprite_041_back.bmp	./xpm/sprite_041_back.xpm 2>/dev/null
convert ./bmp/sprite_042_front.bmp	./xpm/sprite_042_front.xpm 2>/dev/null
convert ./bmp/sprite_042_back.bmp	./xpm/sprite_042_back.xpm 2>/dev/null
convert ./bmp/sprite_043_front.bmp	./xpm/sprite_043_front.xpm 2>/dev/null
convert ./bmp/sprite_043_back.bmp	./xpm/sprite_043_back.xpm 2>/dev/null
convert ./bmp/sprite_044_front.bmp	./xpm/sprite_044_front.xpm 2>/dev/null
convert ./bmp/sprite_044_back.bmp	./xpm/sprite_044_back.xpm 2>/dev/null
convert ./bmp/sprite_045_front.bmp	./xpm/sprite_045_front.xpm 2>/dev/null
convert ./bmp/sprite_045_back.bmp	./xpm/sprite_045_back.xpm 2>/dev/null
convert ./bmp/sprite_046_front.bmp	./xpm/sprite_046_front.xpm 2>/dev/null
convert ./bmp/sprite_046_back.bmp	./xpm/sprite_046_back.xpm 2>/dev/null
convert ./bmp/sprite_047_front.bmp	./xpm/sprite_047_front.xpm 2>/dev/null
convert ./bmp/sprite_047_back.bmp	./xpm/sprite_047_back.xpm 2>/dev/null
convert ./bmp/sprite_048_front.bmp	./xpm/sprite_048_front.xpm 2>/dev/null
convert ./bmp/sprite_048_back.bmp	./xpm/sprite_048_back.xpm 2>/dev/null
convert ./bmp/sprite_049_front.bmp	./xpm/sprite_049_front.xpm 2>/dev/null
convert ./bmp/sprite_049_back.bmp	./xpm/sprite_049_back.xpm 2>/dev/null
convert ./bmp/sprite_050_front.bmp	./xpm/sprite_050_front.xpm 2>/dev/null
convert ./bmp/sprite_050_back.bmp	./xpm/sprite_050_back.xpm 2>/dev/null
convert ./bmp/sprite_051_front.bmp	./xpm/sprite_051_front.xpm 2>/dev/null
convert ./bmp/sprite_051_back.bmp	./xpm/sprite_051_back.xpm 2>/dev/null
convert ./bmp/sprite_052_front.bmp	./xpm/sprite_052_front.xpm 2>/dev/null
convert ./bmp/sprite_052_back.bmp	./xpm/sprite_052_back.xpm 2>/dev/null
convert ./bmp/sprite_053_front.bmp	./xpm/sprite_053_front.xpm 2>/dev/null
convert ./bmp/sprite_053_back.bmp	./xpm/sprite_053_back.xpm 2>/dev/null
convert ./bmp/sprite_054_front.bmp	./xpm/sprite_054_front.xpm 2>/dev/null
convert ./bmp/sprite_054_back.bmp	./xpm/sprite_054_back.xpm 2>/dev/null
convert ./bmp/sprite_055_front.bmp	./xpm/sprite_055_front.xpm 2>/dev/null
convert ./bmp/sprite_055_back.bmp	./xpm/sprite_055_back.xpm 2>/dev/null
convert ./bmp/sprite_056_front.bmp	./xpm/sprite_056_front.xpm 2>/dev/null
convert ./bmp/sprite_056_back.bmp	./xpm/sprite_056_back.xpm 2>/dev/null
convert ./bmp/sprite_057_front.bmp	./xpm/sprite_057_front.xpm 2>/dev/null
convert ./bmp/sprite_057_back.bmp	./xpm/sprite_057_back.xpm 2>/dev/null
convert ./bmp/sprite_058_front.bmp	./xpm/sprite_058_front.xpm 2>/dev/null
convert ./bmp/sprite_058_back.bmp	./xpm/sprite_058_back.xpm 2>/dev/null
convert ./bmp/sprite_059_front.bmp	./xpm/sprite_059_front.xpm 2>/dev/null
convert ./bmp/sprite_059_back.bmp	./xpm/sprite_059_back.xpm 2>/dev/null
convert ./bmp/sprite_060_front.bmp	./xpm/sprite_060_front.xpm 2>/dev/null
convert ./bmp/sprite_060_back.bmp	./xpm/sprite_060_back.xpm 2>/dev/null
convert ./bmp/sprite_061_front.bmp	./xpm/sprite_061_front.xpm 2>/dev/null
convert ./bmp/sprite_061_back.bmp	./xpm/sprite_061_back.xpm 2>/dev/null
convert ./bmp/sprite_062_front.bmp	./xpm/sprite_062_front.xpm 2>/dev/null
convert ./bmp/sprite_062_back.bmp	./xpm/sprite_062_back.xpm 2>/dev/null
convert ./bmp/sprite_063_front.bmp	./xpm/sprite_063_front.xpm 2>/dev/null
convert ./bmp/sprite_063_back.bmp	./xpm/sprite_063_back.xpm 2>/dev/null
convert ./bmp/sprite_064_front.bmp	./xpm/sprite_064_front.xpm 2>/dev/null
convert ./bmp/sprite_064_back.bmp	./xpm/sprite_064_back.xpm 2>/dev/null
convert ./bmp/sprite_065_front.bmp	./xpm/sprite_065_front.xpm 2>/dev/null
convert ./bmp/sprite_065_back.bmp	./xpm/sprite_065_back.xpm 2>/dev/null
convert ./bmp/sprite_066_front.bmp	./xpm/sprite_066_front.xpm 2>/dev/null
convert ./bmp/sprite_066_back.bmp	./xpm/sprite_066_back.xpm 2>/dev/null
convert ./bmp/sprite_067_front.bmp	./xpm/sprite_067_front.xpm 2>/dev/null
convert ./bmp/sprite_067_back.bmp	./xpm/sprite_067_back.xpm 2>/dev/null
convert ./bmp/sprite_068_front.bmp	./xpm/sprite_068_front.xpm 2>/dev/null
convert ./bmp/sprite_068_back.bmp	./xpm/sprite_068_back.xpm 2>/dev/null
convert ./bmp/sprite_069_front.bmp	./xpm/sprite_069_front.xpm 2>/dev/null
convert ./bmp/sprite_069_back.bmp	./xpm/sprite_069_back.xpm 2>/dev/null
convert ./bmp/sprite_070_front.bmp	./xpm/sprite_070_front.xpm 2>/dev/null
convert ./bmp/sprite_070_back.bmp	./xpm/sprite_070_back.xpm 2>/dev/null
convert ./bmp/sprite_071_front.bmp	./xpm/sprite_071_front.xpm 2>/dev/null
convert ./bmp/sprite_071_back.bmp	./xpm/sprite_071_back.xpm 2>/dev/null
convert ./bmp/sprite_072_front.bmp	./xpm/sprite_072_front.xpm 2>/dev/null
convert ./bmp/sprite_072_back.bmp	./xpm/sprite_072_back.xpm 2>/dev/null
convert ./bmp/sprite_073_front.bmp	./xpm/sprite_073_front.xpm 2>/dev/null
convert ./bmp/sprite_073_back.bmp	./xpm/sprite_073_back.xpm 2>/dev/null
convert ./bmp/sprite_074_front.bmp	./xpm/sprite_074_front.xpm 2>/dev/null
convert ./bmp/sprite_074_back.bmp	./xpm/sprite_074_back.xpm 2>/dev/null
convert ./bmp/sprite_075_front.bmp	./xpm/sprite_075_front.xpm 2>/dev/null
convert ./bmp/sprite_075_back.bmp	./xpm/sprite_075_back.xpm 2>/dev/null
convert ./bmp/sprite_076_front.bmp	./xpm/sprite_076_front.xpm 2>/dev/null
convert ./bmp/sprite_076_back.bmp	./xpm/sprite_076_back.xpm 2>/dev/null
convert ./bmp/sprite_077_front.bmp	./xpm/sprite_077_front.xpm 2>/dev/null
convert ./bmp/sprite_077_back.bmp	./xpm/sprite_077_back.xpm 2>/dev/null
convert ./bmp/sprite_078_front.bmp	./xpm/sprite_078_front.xpm 2>/dev/null
convert ./bmp/sprite_078_back.bmp	./xpm/sprite_078_back.xpm 2>/dev/null
convert ./bmp/sprite_079_front.bmp	./xpm/sprite_079_front.xpm 2>/dev/null
convert ./bmp/sprite_079_back.bmp	./xpm/sprite_079_back.xpm 2>/dev/null
convert ./bmp/sprite_080_front.bmp	./xpm/sprite_080_front.xpm 2>/dev/null
convert ./bmp/sprite_080_back.bmp	./xpm/sprite_080_back.xpm 2>/dev/null
convert ./bmp/sprite_081_front.bmp	./xpm/sprite_081_front.xpm 2>/dev/null
convert ./bmp/sprite_081_back.bmp	./xpm/sprite_081_back.xpm 2>/dev/null
convert ./bmp/sprite_082_front.bmp	./xpm/sprite_082_front.xpm 2>/dev/null
convert ./bmp/sprite_082_back.bmp	./xpm/sprite_082_back.xpm 2>/dev/null
convert ./bmp/sprite_083_front.bmp	./xpm/sprite_083_front.xpm 2>/dev/null
convert ./bmp/sprite_083_back.bmp	./xpm/sprite_083_back.xpm 2>/dev/null
convert ./bmp/sprite_084_front.bmp	./xpm/sprite_084_front.xpm 2>/dev/null
convert ./bmp/sprite_084_back.bmp	./xpm/sprite_084_back.xpm 2>/dev/null
convert ./bmp/sprite_085_front.bmp	./xpm/sprite_085_front.xpm 2>/dev/null
convert ./bmp/sprite_085_back.bmp	./xpm/sprite_085_back.xpm 2>/dev/null
convert ./bmp/sprite_086_front.bmp	./xpm/sprite_086_front.xpm 2>/dev/null
convert ./bmp/sprite_086_back.bmp	./xpm/sprite_086_back.xpm 2>/dev/null
convert ./bmp/sprite_087_front.bmp	./xpm/sprite_087_front.xpm 2>/dev/null
convert ./bmp/sprite_087_back.bmp	./xpm/sprite_087_back.xpm 2>/dev/null
convert ./bmp/sprite_088_front.bmp	./xpm/sprite_088_front.xpm 2>/dev/null
convert ./bmp/sprite_088_back.bmp	./xpm/sprite_088_back.xpm 2>/dev/null
convert ./bmp/sprite_089_front.bmp	./xpm/sprite_089_front.xpm 2>/dev/null
convert ./bmp/sprite_089_back.bmp	./xpm/sprite_089_back.xpm 2>/dev/null
convert ./bmp/sprite_090_front.bmp	./xpm/sprite_090_front.xpm 2>/dev/null
convert ./bmp/sprite_090_back.bmp	./xpm/sprite_090_back.xpm 2>/dev/null
convert ./bmp/sprite_091_front.bmp	./xpm/sprite_091_front.xpm 2>/dev/null
convert ./bmp/sprite_091_back.bmp	./xpm/sprite_091_back.xpm 2>/dev/null
convert ./bmp/sprite_092_front.bmp	./xpm/sprite_092_front.xpm 2>/dev/null
convert ./bmp/sprite_092_back.bmp	./xpm/sprite_092_back.xpm 2>/dev/null
convert ./bmp/sprite_093_front.bmp	./xpm/sprite_093_front.xpm 2>/dev/null
convert ./bmp/sprite_093_back.bmp	./xpm/sprite_093_back.xpm 2>/dev/null
convert ./bmp/sprite_094_front.bmp	./xpm/sprite_094_front.xpm 2>/dev/null
convert ./bmp/sprite_094_back.bmp	./xpm/sprite_094_back.xpm 2>/dev/null
convert ./bmp/sprite_095_front.bmp	./xpm/sprite_095_front.xpm 2>/dev/null
convert ./bmp/sprite_095_back.bmp	./xpm/sprite_095_back.xpm 2>/dev/null
convert ./bmp/sprite_096_front.bmp	./xpm/sprite_096_front.xpm 2>/dev/null
convert ./bmp/sprite_096_back.bmp	./xpm/sprite_096_back.xpm 2>/dev/null
convert ./bmp/sprite_097_front.bmp	./xpm/sprite_097_front.xpm 2>/dev/null
convert ./bmp/sprite_097_back.bmp	./xpm/sprite_097_back.xpm 2>/dev/null
convert ./bmp/sprite_098_front.bmp	./xpm/sprite_098_front.xpm 2>/dev/null
convert ./bmp/sprite_098_back.bmp	./xpm/sprite_098_back.xpm 2>/dev/null
convert ./bmp/sprite_099_front.bmp	./xpm/sprite_099_front.xpm 2>/dev/null
convert ./bmp/sprite_099_back.bmp	./xpm/sprite_099_back.xpm 2>/dev/null
convert ./bmp/sprite_100_front.bmp	./xpm/sprite_100_front.xpm 2>/dev/null
convert ./bmp/sprite_100_back.bmp	./xpm/sprite_100_back.xpm 2>/dev/null
convert ./bmp/sprite_101_front.bmp	./xpm/sprite_101_front.xpm 2>/dev/null
convert ./bmp/sprite_101_back.bmp	./xpm/sprite_101_back.xpm 2>/dev/null
convert ./bmp/sprite_102_front.bmp	./xpm/sprite_102_front.xpm 2>/dev/null
convert ./bmp/sprite_102_back.bmp	./xpm/sprite_102_back.xpm 2>/dev/null
convert ./bmp/sprite_103_front.bmp	./xpm/sprite_103_front.xpm 2>/dev/null
convert ./bmp/sprite_103_back.bmp	./xpm/sprite_103_back.xpm 2>/dev/null
convert ./bmp/sprite_104_front.bmp	./xpm/sprite_104_front.xpm 2>/dev/null
convert ./bmp/sprite_104_back.bmp	./xpm/sprite_104_back.xpm 2>/dev/null
convert ./bmp/sprite_105_front.bmp	./xpm/sprite_105_front.xpm 2>/dev/null
convert ./bmp/sprite_105_back.bmp	./xpm/sprite_105_back.xpm 2>/dev/null
convert ./bmp/sprite_106_front.bmp	./xpm/sprite_106_front.xpm 2>/dev/null
convert ./bmp/sprite_106_back.bmp	./xpm/sprite_106_back.xpm 2>/dev/null
convert ./bmp/sprite_107_front.bmp	./xpm/sprite_107_front.xpm 2>/dev/null
convert ./bmp/sprite_107_back.bmp	./xpm/sprite_107_back.xpm 2>/dev/null
convert ./bmp/sprite_108_front.bmp	./xpm/sprite_108_front.xpm 2>/dev/null
convert ./bmp/sprite_108_back.bmp	./xpm/sprite_108_back.xpm 2>/dev/null
convert ./bmp/sprite_109_front.bmp	./xpm/sprite_109_front.xpm 2>/dev/null
convert ./bmp/sprite_109_back.bmp	./xpm/sprite_109_back.xpm 2>/dev/null
convert ./bmp/sprite_110_front.bmp	./xpm/sprite_110_front.xpm 2>/dev/null
convert ./bmp/sprite_110_back.bmp	./xpm/sprite_110_back.xpm 2>/dev/null
convert ./bmp/sprite_111_front.bmp	./xpm/sprite_111_front.xpm 2>/dev/null
convert ./bmp/sprite_111_back.bmp	./xpm/sprite_111_back.xpm 2>/dev/null
convert ./bmp/sprite_112_front.bmp	./xpm/sprite_112_front.xpm 2>/dev/null
convert ./bmp/sprite_112_back.bmp	./xpm/sprite_112_back.xpm 2>/dev/null
convert ./bmp/sprite_113_front.bmp	./xpm/sprite_113_front.xpm 2>/dev/null
convert ./bmp/sprite_113_back.bmp	./xpm/sprite_113_back.xpm 2>/dev/null
convert ./bmp/sprite_114_front.bmp	./xpm/sprite_114_front.xpm 2>/dev/null
convert ./bmp/sprite_114_back.bmp	./xpm/sprite_114_back.xpm 2>/dev/null
convert ./bmp/sprite_115_front.bmp	./xpm/sprite_115_front.xpm 2>/dev/null
convert ./bmp/sprite_115_back.bmp	./xpm/sprite_115_back.xpm 2>/dev/null
convert ./bmp/sprite_116_front.bmp	./xpm/sprite_116_front.xpm 2>/dev/null
convert ./bmp/sprite_116_back.bmp	./xpm/sprite_116_back.xpm 2>/dev/null
convert ./bmp/sprite_117_front.bmp	./xpm/sprite_117_front.xpm 2>/dev/null
convert ./bmp/sprite_117_back.bmp	./xpm/sprite_117_back.xpm 2>/dev/null
convert ./bmp/sprite_118_front.bmp	./xpm/sprite_118_front.xpm 2>/dev/null
convert ./bmp/sprite_118_back.bmp	./xpm/sprite_118_back.xpm 2>/dev/null
convert ./bmp/sprite_119_front.bmp	./xpm/sprite_119_front.xpm 2>/dev/null
convert ./bmp/sprite_119_back.bmp	./xpm/sprite_119_back.xpm 2>/dev/null
convert ./bmp/sprite_120_front.bmp	./xpm/sprite_120_front.xpm 2>/dev/null
convert ./bmp/sprite_120_back.bmp	./xpm/sprite_120_back.xpm 2>/dev/null
convert ./bmp/sprite_121_front.bmp	./xpm/sprite_121_front.xpm 2>/dev/null
convert ./bmp/sprite_121_back.bmp	./xpm/sprite_121_back.xpm 2>/dev/null
convert ./bmp/sprite_122_front.bmp	./xpm/sprite_122_front.xpm 2>/dev/null
convert ./bmp/sprite_122_back.bmp	./xpm/sprite_122_back.xpm 2>/dev/null
convert ./bmp/sprite_123_front.bmp	./xpm/sprite_123_front.xpm 2>/dev/null
convert ./bmp/sprite_123_back.bmp	./xpm/sprite_123_back.xpm 2>/dev/null
convert ./bmp/sprite_124_front.bmp	./xpm/sprite_124_front.xpm 2>/dev/null
convert ./bmp/sprite_124_back.bmp	./xpm/sprite_124_back.xpm 2>/dev/null
convert ./bmp/sprite_125_front.bmp	./xpm/sprite_125_front.xpm 2>/dev/null
convert ./bmp/sprite_125_back.bmp	./xpm/sprite_125_back.xpm 2>/dev/null
convert ./bmp/sprite_126_front.bmp	./xpm/sprite_126_front.xpm 2>/dev/null
convert ./bmp/sprite_126_back.bmp	./xpm/sprite_126_back.xpm 2>/dev/null
convert ./bmp/sprite_127_front.bmp	./xpm/sprite_127_front.xpm 2>/dev/null
convert ./bmp/sprite_127_back.bmp	./xpm/sprite_127_back.xpm 2>/dev/null
convert ./bmp/sprite_128_front.bmp	./xpm/sprite_128_front.xpm 2>/dev/null
convert ./bmp/sprite_128_back.bmp	./xpm/sprite_128_back.xpm 2>/dev/null
convert ./bmp/sprite_129_front.bmp	./xpm/sprite_129_front.xpm 2>/dev/null
convert ./bmp/sprite_129_back.bmp	./xpm/sprite_129_back.xpm 2>/dev/null
convert ./bmp/sprite_130_front.bmp	./xpm/sprite_130_front.xpm 2>/dev/null
convert ./bmp/sprite_130_back.bmp	./xpm/sprite_130_back.xpm 2>/dev/null
convert ./bmp/sprite_131_front.bmp	./xpm/sprite_131_front.xpm 2>/dev/null
convert ./bmp/sprite_131_back.bmp	./xpm/sprite_131_back.xpm 2>/dev/null
convert ./bmp/sprite_132_front.bmp	./xpm/sprite_132_front.xpm 2>/dev/null
convert ./bmp/sprite_132_back.bmp	./xpm/sprite_132_back.xpm 2>/dev/null
convert ./bmp/sprite_133_front.bmp	./xpm/sprite_133_front.xpm 2>/dev/null
convert ./bmp/sprite_133_back.bmp	./xpm/sprite_133_back.xpm 2>/dev/null
convert ./bmp/sprite_134_front.bmp	./xpm/sprite_134_front.xpm 2>/dev/null
convert ./bmp/sprite_134_back.bmp	./xpm/sprite_134_back.xpm 2>/dev/null
convert ./bmp/sprite_135_front.bmp	./xpm/sprite_135_front.xpm 2>/dev/null
convert ./bmp/sprite_135_back.bmp	./xpm/sprite_135_back.xpm 2>/dev/null
convert ./bmp/sprite_136_front.bmp	./xpm/sprite_136_front.xpm 2>/dev/null
convert ./bmp/sprite_136_back.bmp	./xpm/sprite_136_back.xpm 2>/dev/null
convert ./bmp/sprite_137_front.bmp	./xpm/sprite_137_front.xpm 2>/dev/null
convert ./bmp/sprite_137_back.bmp	./xpm/sprite_137_back.xpm 2>/dev/null
convert ./bmp/sprite_138_front.bmp	./xpm/sprite_138_front.xpm 2>/dev/null
convert ./bmp/sprite_138_back.bmp	./xpm/sprite_138_back.xpm 2>/dev/null
convert ./bmp/sprite_139_front.bmp	./xpm/sprite_139_front.xpm 2>/dev/null
convert ./bmp/sprite_139_back.bmp	./xpm/sprite_139_back.xpm 2>/dev/null
convert ./bmp/sprite_140_front.bmp	./xpm/sprite_140_front.xpm 2>/dev/null
convert ./bmp/sprite_140_back.bmp	./xpm/sprite_140_back.xpm 2>/dev/null
convert ./bmp/sprite_141_front.bmp	./xpm/sprite_141_front.xpm 2>/dev/null
convert ./bmp/sprite_141_back.bmp	./xpm/sprite_141_back.xpm 2>/dev/null
convert ./bmp/sprite_142_front.bmp	./xpm/sprite_142_front.xpm 2>/dev/null
convert ./bmp/sprite_142_back.bmp	./xpm/sprite_142_back.xpm 2>/dev/null
convert ./bmp/sprite_143_front.bmp	./xpm/sprite_143_front.xpm 2>/dev/null
convert ./bmp/sprite_143_back.bmp	./xpm/sprite_143_back.xpm 2>/dev/null
convert ./bmp/sprite_144_front.bmp	./xpm/sprite_144_front.xpm 2>/dev/null
convert ./bmp/sprite_144_back.bmp	./xpm/sprite_144_back.xpm 2>/dev/null
convert ./bmp/sprite_145_front.bmp	./xpm/sprite_145_front.xpm 2>/dev/null
convert ./bmp/sprite_145_back.bmp	./xpm/sprite_145_back.xpm 2>/dev/null
convert ./bmp/sprite_146_front.bmp	./xpm/sprite_146_front.xpm 2>/dev/null
convert ./bmp/sprite_146_back.bmp	./xpm/sprite_146_back.xpm 2>/dev/null
convert ./bmp/sprite_147_front.bmp	./xpm/sprite_147_front.xpm 2>/dev/null
convert ./bmp/sprite_147_back.bmp	./xpm/sprite_147_back.xpm 2>/dev/null
convert ./bmp/sprite_148_front.bmp	./xpm/sprite_148_front.xpm 2>/dev/null
convert ./bmp/sprite_148_back.bmp	./xpm/sprite_148_back.xpm 2>/dev/null
convert ./bmp/sprite_149_front.bmp	./xpm/sprite_149_front.xpm 2>/dev/null
convert ./bmp/sprite_149_back.bmp	./xpm/sprite_149_back.xpm 2>/dev/null
convert ./bmp/sprite_150_front.bmp	./xpm/sprite_150_front.xpm 2>/dev/null
convert ./bmp/sprite_150_back.bmp	./xpm/sprite_150_back.xpm 2>/dev/null
convert ./bmp/sprite_151_front.bmp	./xpm/sprite_151_front.xpm 2>/dev/null
convert ./bmp/sprite_151_back.bmp	./xpm/sprite_151_back.xpm 2>/dev/null
convert ./bmp/sprite_152_front.bmp	./xpm/sprite_152_front.xpm 2>/dev/null
convert ./bmp/sprite_152_back.bmp	./xpm/sprite_152_back.xpm 2>/dev/null
convert ./bmp/sprite_153_front.bmp	./xpm/sprite_153_front.xpm 2>/dev/null
convert ./bmp/sprite_153_back.bmp	./xpm/sprite_153_back.xpm 2>/dev/null
convert ./bmp/sprite_154_front.bmp	./xpm/sprite_154_front.xpm 2>/dev/null
convert ./bmp/sprite_154_back.bmp	./xpm/sprite_154_back.xpm 2>/dev/null
convert ./bmp/sprite_155_front.bmp	./xpm/sprite_155_front.xpm 2>/dev/null
convert ./bmp/sprite_155_back.bmp	./xpm/sprite_155_back.xpm 2>/dev/null
convert ./bmp/sprite_156_front.bmp	./xpm/sprite_156_front.xpm 2>/dev/null
convert ./bmp/sprite_156_back.bmp	./xpm/sprite_156_back.xpm 2>/dev/null
convert ./bmp/sprite_157_front.bmp	./xpm/sprite_157_front.xpm 2>/dev/null
convert ./bmp/sprite_157_back.bmp	./xpm/sprite_157_back.xpm 2>/dev/null
convert ./bmp/sprite_158_front.bmp	./xpm/sprite_158_front.xpm 2>/dev/null
convert ./bmp/sprite_158_back.bmp	./xpm/sprite_158_back.xpm 2>/dev/null
convert ./bmp/sprite_159_front.bmp	./xpm/sprite_159_front.xpm 2>/dev/null
convert ./bmp/sprite_159_back.bmp	./xpm/sprite_159_back.xpm 2>/dev/null
convert ./bmp/sprite_160_front.bmp	./xpm/sprite_160_front.xpm 2>/dev/null
convert ./bmp/sprite_160_back.bmp	./xpm/sprite_160_back.xpm 2>/dev/null
convert ./bmp/sprite_161_front.bmp	./xpm/sprite_161_front.xpm 2>/dev/null
convert ./bmp/sprite_161_back.bmp	./xpm/sprite_161_back.xpm 2>/dev/null
convert ./bmp/sprite_162_front.bmp	./xpm/sprite_162_front.xpm 2>/dev/null
convert ./bmp/sprite_162_back.bmp	./xpm/sprite_162_back.xpm 2>/dev/null
convert ./bmp/sprite_163_front.bmp	./xpm/sprite_163_front.xpm 2>/dev/null
convert ./bmp/sprite_163_back.bmp	./xpm/sprite_163_back.xpm 2>/dev/null
convert ./bmp/sprite_164_front.bmp	./xpm/sprite_164_front.xpm 2>/dev/null
convert ./bmp/sprite_164_back.bmp	./xpm/sprite_164_back.xpm 2>/dev/null
convert ./bmp/sprite_165_front.bmp	./xpm/sprite_165_front.xpm 2>/dev/null
convert ./bmp/sprite_165_back.bmp	./xpm/sprite_165_back.xpm 2>/dev/null
convert ./bmp/sprite_166_front.bmp	./xpm/sprite_166_front.xpm 2>/dev/null
convert ./bmp/sprite_166_back.bmp	./xpm/sprite_166_back.xpm 2>/dev/null
convert ./bmp/sprite_167_front.bmp	./xpm/sprite_167_front.xpm 2>/dev/null
convert ./bmp/sprite_167_back.bmp	./xpm/sprite_167_back.xpm 2>/dev/null
convert ./bmp/sprite_168_front.bmp	./xpm/sprite_168_front.xpm 2>/dev/null
convert ./bmp/sprite_168_back.bmp	./xpm/sprite_168_back.xpm 2>/dev/null
convert ./bmp/sprite_169_front.bmp	./xpm/sprite_169_front.xpm 2>/dev/null
convert ./bmp/sprite_169_back.bmp	./xpm/sprite_169_back.xpm 2>/dev/null
convert ./bmp/sprite_170_front.bmp	./xpm/sprite_170_front.xpm 2>/dev/null
convert ./bmp/sprite_170_back.bmp	./xpm/sprite_170_back.xpm 2>/dev/null
convert ./bmp/sprite_171_front.bmp	./xpm/sprite_171_front.xpm 2>/dev/null
convert ./bmp/sprite_171_back.bmp	./xpm/sprite_171_back.xpm 2>/dev/null
convert ./bmp/sprite_172_front.bmp	./xpm/sprite_172_front.xpm 2>/dev/null
convert ./bmp/sprite_172_back.bmp	./xpm/sprite_172_back.xpm 2>/dev/null
convert ./bmp/sprite_173_front.bmp	./xpm/sprite_173_front.xpm 2>/dev/null
convert ./bmp/sprite_173_back.bmp	./xpm/sprite_173_back.xpm 2>/dev/null
convert ./bmp/sprite_174_front.bmp	./xpm/sprite_174_front.xpm 2>/dev/null
convert ./bmp/sprite_174_back.bmp	./xpm/sprite_174_back.xpm 2>/dev/null
convert ./bmp/sprite_175_front.bmp	./xpm/sprite_175_front.xpm 2>/dev/null
convert ./bmp/sprite_175_back.bmp	./xpm/sprite_175_back.xpm 2>/dev/null
convert ./bmp/sprite_176_front.bmp	./xpm/sprite_176_front.xpm 2>/dev/null
convert ./bmp/sprite_176_back.bmp	./xpm/sprite_176_back.xpm 2>/dev/null
convert ./bmp/sprite_177_front.bmp	./xpm/sprite_177_front.xpm 2>/dev/null
convert ./bmp/sprite_177_back.bmp	./xpm/sprite_177_back.xpm 2>/dev/null
convert ./bmp/sprite_178_front.bmp	./xpm/sprite_178_front.xpm 2>/dev/null
convert ./bmp/sprite_178_back.bmp	./xpm/sprite_178_back.xpm 2>/dev/null
convert ./bmp/sprite_179_front.bmp	./xpm/sprite_179_front.xpm 2>/dev/null
convert ./bmp/sprite_179_back.bmp	./xpm/sprite_179_back.xpm 2>/dev/null
convert ./bmp/sprite_180_front.bmp	./xpm/sprite_180_front.xpm 2>/dev/null
convert ./bmp/sprite_180_back.bmp	./xpm/sprite_180_back.xpm 2>/dev/null
convert ./bmp/sprite_181_front.bmp	./xpm/sprite_181_front.xpm 2>/dev/null
convert ./bmp/sprite_181_back.bmp	./xpm/sprite_181_back.xpm 2>/dev/null
convert ./bmp/sprite_182_front.bmp	./xpm/sprite_182_front.xpm 2>/dev/null
convert ./bmp/sprite_182_back.bmp	./xpm/sprite_182_back.xpm 2>/dev/null
convert ./bmp/sprite_183_front.bmp	./xpm/sprite_183_front.xpm 2>/dev/null
convert ./bmp/sprite_183_back.bmp	./xpm/sprite_183_back.xpm 2>/dev/null
convert ./bmp/sprite_184_front.bmp	./xpm/sprite_184_front.xpm 2>/dev/null
convert ./bmp/sprite_184_back.bmp	./xpm/sprite_184_back.xpm 2>/dev/null
convert ./bmp/sprite_185_front.bmp	./xpm/sprite_185_front.xpm 2>/dev/null
convert ./bmp/sprite_185_back.bmp	./xpm/sprite_185_back.xpm 2>/dev/null
convert ./bmp/sprite_186_front.bmp	./xpm/sprite_186_front.xpm 2>/dev/null
convert ./bmp/sprite_186_back.bmp	./xpm/sprite_186_back.xpm 2>/dev/null
convert ./bmp/sprite_187_front.bmp	./xpm/sprite_187_front.xpm 2>/dev/null
convert ./bmp/sprite_187_back.bmp	./xpm/sprite_187_back.xpm 2>/dev/null
convert ./bmp/sprite_188_front.bmp	./xpm/sprite_188_front.xpm 2>/dev/null
convert ./bmp/sprite_188_back.bmp	./xpm/sprite_188_back.xpm 2>/dev/null
convert ./bmp/sprite_189_front.bmp	./xpm/sprite_189_front.xpm 2>/dev/null
convert ./bmp/sprite_189_back.bmp	./xpm/sprite_189_back.xpm 2>/dev/null
convert ./bmp/sprite_190_front.bmp	./xpm/sprite_190_front.xpm 2>/dev/null
convert ./bmp/sprite_190_back.bmp	./xpm/sprite_190_back.xpm 2>/dev/null
convert ./bmp/sprite_191_front.bmp	./xpm/sprite_191_front.xpm 2>/dev/null
convert ./bmp/sprite_191_back.bmp	./xpm/sprite_191_back.xpm 2>/dev/null
convert ./bmp/sprite_192_front.bmp	./xpm/sprite_192_front.xpm 2>/dev/null
convert ./bmp/sprite_192_back.bmp	./xpm/sprite_192_back.xpm 2>/dev/null
convert ./bmp/sprite_193_front.bmp	./xpm/sprite_193_front.xpm 2>/dev/null
convert ./bmp/sprite_193_back.bmp	./xpm/sprite_193_back.xpm 2>/dev/null
convert ./bmp/sprite_194_front.bmp	./xpm/sprite_194_front.xpm 2>/dev/null
convert ./bmp/sprite_194_back.bmp	./xpm/sprite_194_back.xpm 2>/dev/null
convert ./bmp/sprite_195_front.bmp	./xpm/sprite_195_front.xpm 2>/dev/null
convert ./bmp/sprite_195_back.bmp	./xpm/sprite_195_back.xpm 2>/dev/null
convert ./bmp/sprite_196_front.bmp	./xpm/sprite_196_front.xpm 2>/dev/null
convert ./bmp/sprite_196_back.bmp	./xpm/sprite_196_back.xpm 2>/dev/null
convert ./bmp/sprite_197_front.bmp	./xpm/sprite_197_front.xpm 2>/dev/null
convert ./bmp/sprite_197_back.bmp	./xpm/sprite_197_back.xpm 2>/dev/null
convert ./bmp/sprite_198_front.bmp	./xpm/sprite_198_front.xpm 2>/dev/null
convert ./bmp/sprite_198_back.bmp	./xpm/sprite_198_back.xpm 2>/dev/null
convert ./bmp/sprite_199_front.bmp	./xpm/sprite_199_front.xpm 2>/dev/null
convert ./bmp/sprite_199_back.bmp	./xpm/sprite_199_back.xpm 2>/dev/null
convert ./bmp/sprite_200_front.bmp	./xpm/sprite_200_front.xpm 2>/dev/null
convert ./bmp/sprite_200_back.bmp	./xpm/sprite_200_back.xpm 2>/dev/null
convert ./bmp/sprite_201_front.bmp	./xpm/sprite_201_front.xpm 2>/dev/null
convert ./bmp/sprite_201_back.bmp	./xpm/sprite_201_back.xpm 2>/dev/null
convert ./bmp/sprite_202_front.bmp	./xpm/sprite_202_front.xpm 2>/dev/null
convert ./bmp/sprite_202_back.bmp	./xpm/sprite_202_back.xpm 2>/dev/null
convert ./bmp/sprite_203_front.bmp	./xpm/sprite_203_front.xpm 2>/dev/null
convert ./bmp/sprite_203_back.bmp	./xpm/sprite_203_back.xpm 2>/dev/null
convert ./bmp/sprite_204_front.bmp	./xpm/sprite_204_front.xpm 2>/dev/null
convert ./bmp/sprite_204_back.bmp	./xpm/sprite_204_back.xpm 2>/dev/null
convert ./bmp/sprite_205_front.bmp	./xpm/sprite_205_front.xpm 2>/dev/null
convert ./bmp/sprite_205_back.bmp	./xpm/sprite_205_back.xpm 2>/dev/null
convert ./bmp/sprite_206_front.bmp	./xpm/sprite_206_front.xpm 2>/dev/null
convert ./bmp/sprite_206_back.bmp	./xpm/sprite_206_back.xpm 2>/dev/null
convert ./bmp/sprite_207_front.bmp	./xpm/sprite_207_front.xpm 2>/dev/null
convert ./bmp/sprite_207_back.bmp	./xpm/sprite_207_back.xpm 2>/dev/null
convert ./bmp/sprite_208_front.bmp	./xpm/sprite_208_front.xpm 2>/dev/null
convert ./bmp/sprite_208_back.bmp	./xpm/sprite_208_back.xpm 2>/dev/null
convert ./bmp/sprite_209_front.bmp	./xpm/sprite_209_front.xpm 2>/dev/null
convert ./bmp/sprite_209_back.bmp	./xpm/sprite_209_back.xpm 2>/dev/null
convert ./bmp/sprite_210_front.bmp	./xpm/sprite_210_front.xpm 2>/dev/null
convert ./bmp/sprite_210_back.bmp	./xpm/sprite_210_back.xpm 2>/dev/null
convert ./bmp/sprite_211_front.bmp	./xpm/sprite_211_front.xpm 2>/dev/null
convert ./bmp/sprite_211_back.bmp	./xpm/sprite_211_back.xpm 2>/dev/null
convert ./bmp/sprite_212_front.bmp	./xpm/sprite_212_front.xpm 2>/dev/null
convert ./bmp/sprite_212_back.bmp	./xpm/sprite_212_back.xpm 2>/dev/null
convert ./bmp/sprite_213_front.bmp	./xpm/sprite_213_front.xpm 2>/dev/null
convert ./bmp/sprite_213_back.bmp	./xpm/sprite_213_back.xpm 2>/dev/null
convert ./bmp/sprite_214_front.bmp	./xpm/sprite_214_front.xpm 2>/dev/null
convert ./bmp/sprite_214_back.bmp	./xpm/sprite_214_back.xpm 2>/dev/null
convert ./bmp/sprite_215_front.bmp	./xpm/sprite_215_front.xpm 2>/dev/null
convert ./bmp/sprite_215_back.bmp	./xpm/sprite_215_back.xpm 2>/dev/null
convert ./bmp/sprite_216_front.bmp	./xpm/sprite_216_front.xpm 2>/dev/null
convert ./bmp/sprite_216_back.bmp	./xpm/sprite_216_back.xpm 2>/dev/null
convert ./bmp/sprite_217_front.bmp	./xpm/sprite_217_front.xpm 2>/dev/null
convert ./bmp/sprite_217_back.bmp	./xpm/sprite_217_back.xpm 2>/dev/null
convert ./bmp/sprite_218_front.bmp	./xpm/sprite_218_front.xpm 2>/dev/null
convert ./bmp/sprite_218_back.bmp	./xpm/sprite_218_back.xpm 2>/dev/null
convert ./bmp/sprite_219_front.bmp	./xpm/sprite_219_front.xpm 2>/dev/null
convert ./bmp/sprite_219_back.bmp	./xpm/sprite_219_back.xpm 2>/dev/null
convert ./bmp/sprite_220_front.bmp	./xpm/sprite_220_front.xpm 2>/dev/null
convert ./bmp/sprite_220_back.bmp	./xpm/sprite_220_back.xpm 2>/dev/null
convert ./bmp/sprite_221_front.bmp	./xpm/sprite_221_front.xpm 2>/dev/null
convert ./bmp/sprite_221_back.bmp	./xpm/sprite_221_back.xpm 2>/dev/null
convert ./bmp/sprite_222_front.bmp	./xpm/sprite_222_front.xpm 2>/dev/null
convert ./bmp/sprite_222_back.bmp	./xpm/sprite_222_back.xpm 2>/dev/null
convert ./bmp/sprite_223_front.bmp	./xpm/sprite_223_front.xpm 2>/dev/null
convert ./bmp/sprite_223_back.bmp	./xpm/sprite_223_back.xpm 2>/dev/null
convert ./bmp/sprite_224_front.bmp	./xpm/sprite_224_front.xpm 2>/dev/null
convert ./bmp/sprite_224_back.bmp	./xpm/sprite_224_back.xpm 2>/dev/null
convert ./bmp/sprite_225_front.bmp	./xpm/sprite_225_front.xpm 2>/dev/null
convert ./bmp/sprite_225_back.bmp	./xpm/sprite_225_back.xpm 2>/dev/null
convert ./bmp/sprite_226_front.bmp	./xpm/sprite_226_front.xpm 2>/dev/null
convert ./bmp/sprite_226_back.bmp	./xpm/sprite_226_back.xpm 2>/dev/null
convert ./bmp/sprite_227_front.bmp	./xpm/sprite_227_front.xpm 2>/dev/null
convert ./bmp/sprite_227_back.bmp	./xpm/sprite_227_back.xpm 2>/dev/null
convert ./bmp/sprite_228_front.bmp	./xpm/sprite_228_front.xpm 2>/dev/null
convert ./bmp/sprite_228_back.bmp	./xpm/sprite_228_back.xpm 2>/dev/null
convert ./bmp/sprite_229_front.bmp	./xpm/sprite_229_front.xpm 2>/dev/null
convert ./bmp/sprite_229_back.bmp	./xpm/sprite_229_back.xpm 2>/dev/null
convert ./bmp/sprite_230_front.bmp	./xpm/sprite_230_front.xpm 2>/dev/null
convert ./bmp/sprite_230_back.bmp	./xpm/sprite_230_back.xpm 2>/dev/null
convert ./bmp/sprite_231_front.bmp	./xpm/sprite_231_front.xpm 2>/dev/null
convert ./bmp/sprite_231_back.bmp	./xpm/sprite_231_back.xpm 2>/dev/null
convert ./bmp/sprite_232_front.bmp	./xpm/sprite_232_front.xpm 2>/dev/null
convert ./bmp/sprite_232_back.bmp	./xpm/sprite_232_back.xpm 2>/dev/null
convert ./bmp/sprite_233_front.bmp	./xpm/sprite_233_front.xpm 2>/dev/null
convert ./bmp/sprite_233_back.bmp	./xpm/sprite_233_back.xpm 2>/dev/null
convert ./bmp/sprite_234_front.bmp	./xpm/sprite_234_front.xpm 2>/dev/null
convert ./bmp/sprite_234_back.bmp	./xpm/sprite_234_back.xpm 2>/dev/null
convert ./bmp/sprite_235_front.bmp	./xpm/sprite_235_front.xpm 2>/dev/null
convert ./bmp/sprite_235_back.bmp	./xpm/sprite_235_back.xpm 2>/dev/null
convert ./bmp/sprite_236_front.bmp	./xpm/sprite_236_front.xpm 2>/dev/null
convert ./bmp/sprite_236_back.bmp	./xpm/sprite_236_back.xpm 2>/dev/null
convert ./bmp/sprite_237_front.bmp	./xpm/sprite_237_front.xpm 2>/dev/null
convert ./bmp/sprite_237_back.bmp	./xpm/sprite_237_back.xpm 2>/dev/null
convert ./bmp/sprite_238_front.bmp	./xpm/sprite_238_front.xpm 2>/dev/null
convert ./bmp/sprite_238_back.bmp	./xpm/sprite_238_back.xpm 2>/dev/null
convert ./bmp/sprite_239_front.bmp	./xpm/sprite_239_front.xpm 2>/dev/null
convert ./bmp/sprite_239_back.bmp	./xpm/sprite_239_back.xpm 2>/dev/null
convert ./bmp/sprite_240_front.bmp	./xpm/sprite_240_front.xpm 2>/dev/null
convert ./bmp/sprite_240_back.bmp	./xpm/sprite_240_back.xpm 2>/dev/null
convert ./bmp/sprite_241_front.bmp	./xpm/sprite_241_front.xpm 2>/dev/null
convert ./bmp/sprite_241_back.bmp	./xpm/sprite_241_back.xpm 2>/dev/null
convert ./bmp/sprite_242_front.bmp	./xpm/sprite_242_front.xpm 2>/dev/null
convert ./bmp/sprite_242_back.bmp	./xpm/sprite_242_back.xpm 2>/dev/null
convert ./bmp/sprite_243_front.bmp	./xpm/sprite_243_front.xpm 2>/dev/null
convert ./bmp/sprite_243_back.bmp	./xpm/sprite_243_back.xpm 2>/dev/null
convert ./bmp/sprite_244_front.bmp	./xpm/sprite_244_front.xpm 2>/dev/null
convert ./bmp/sprite_244_back.bmp	./xpm/sprite_244_back.xpm 2>/dev/null
convert ./bmp/sprite_245_front.bmp	./xpm/sprite_245_front.xpm 2>/dev/null
convert ./bmp/sprite_245_back.bmp	./xpm/sprite_245_back.xpm 2>/dev/null
convert ./bmp/sprite_246_front.bmp	./xpm/sprite_246_front.xpm 2>/dev/null
convert ./bmp/sprite_246_back.bmp	./xpm/sprite_246_back.xpm 2>/dev/null
convert ./bmp/sprite_247_front.bmp	./xpm/sprite_247_front.xpm 2>/dev/null
convert ./bmp/sprite_247_back.bmp	./xpm/sprite_247_back.xpm 2>/dev/null
convert ./bmp/sprite_248_front.bmp	./xpm/sprite_248_front.xpm 2>/dev/null
convert ./bmp/sprite_248_back.bmp	./xpm/sprite_248_back.xpm 2>/dev/null
convert ./bmp/sprite_249_front.bmp	./xpm/sprite_249_front.xpm 2>/dev/null
convert ./bmp/sprite_249_back.bmp	./xpm/sprite_249_back.xpm 2>/dev/null
convert ./bmp/sprite_250_front.bmp	./xpm/sprite_250_front.xpm 2>/dev/null
convert ./bmp/sprite_250_back.bmp	./xpm/sprite_250_back.xpm 2>/dev/null
convert ./bmp/sprite_251_front.bmp	./xpm/sprite_251_front.xpm 2>/dev/null
convert ./bmp/sprite_251_back.bmp	./xpm/sprite_251_back.xpm 2>/dev/null
convert ./bmp/sprite_252_front.bmp	./xpm/sprite_252_front.xpm 2>/dev/null
convert ./bmp/sprite_252_back.bmp	./xpm/sprite_252_back.xpm 2>/dev/null
convert ./bmp/sprite_253_front.bmp	./xpm/sprite_253_front.xpm 2>/dev/null
convert ./bmp/sprite_253_back.bmp	./xpm/sprite_253_back.xpm 2>/dev/null
convert ./bmp/sprite_254_front.bmp	./xpm/sprite_254_front.xpm 2>/dev/null
convert ./bmp/sprite_254_back.bmp	./xpm/sprite_254_back.xpm 2>/dev/null
convert ./bmp/sprite_255_front.bmp	./xpm/sprite_255_front.xpm 2>/dev/null
convert ./bmp/sprite_255_back.bmp	./xpm/sprite_255_back.xpm 2>/dev/null
convert ./bmp/sprite_256_front.bmp	./xpm/sprite_256_front.xpm 2>/dev/null
convert ./bmp/sprite_256_back.bmp	./xpm/sprite_256_back.xpm 2>/dev/null
convert ./bmp/sprite_257_front.bmp	./xpm/sprite_257_front.xpm 2>/dev/null
convert ./bmp/sprite_257_back.bmp	./xpm/sprite_257_back.xpm 2>/dev/null
convert ./bmp/sprite_258_front.bmp	./xpm/sprite_258_front.xpm 2>/dev/null
convert ./bmp/sprite_258_back.bmp	./xpm/sprite_258_back.xpm 2>/dev/null
convert ./bmp/sprite_259_front.bmp	./xpm/sprite_259_front.xpm 2>/dev/null
convert ./bmp/sprite_259_back.bmp	./xpm/sprite_259_back.xpm 2>/dev/null
convert ./bmp/sprite_260_front.bmp	./xpm/sprite_260_front.xpm 2>/dev/null
convert ./bmp/sprite_260_back.bmp	./xpm/sprite_260_back.xpm 2>/dev/null
convert ./bmp/sprite_261_front.bmp	./xpm/sprite_261_front.xpm 2>/dev/null
convert ./bmp/sprite_261_back.bmp	./xpm/sprite_261_back.xpm 2>/dev/null
convert ./bmp/sprite_262_front.bmp	./xpm/sprite_262_front.xpm 2>/dev/null
convert ./bmp/sprite_262_back.bmp	./xpm/sprite_262_back.xpm 2>/dev/null
convert ./bmp/sprite_263_front.bmp	./xpm/sprite_263_front.xpm 2>/dev/null
convert ./bmp/sprite_263_back.bmp	./xpm/sprite_263_back.xpm 2>/dev/null
convert ./bmp/sprite_264_front.bmp	./xpm/sprite_264_front.xpm 2>/dev/null
convert ./bmp/sprite_264_back.bmp	./xpm/sprite_264_back.xpm 2>/dev/null
convert ./bmp/sprite_265_front.bmp	./xpm/sprite_265_front.xpm 2>/dev/null
convert ./bmp/sprite_265_back.bmp	./xpm/sprite_265_back.xpm 2>/dev/null
convert ./bmp/sprite_266_front.bmp	./xpm/sprite_266_front.xpm 2>/dev/null
convert ./bmp/sprite_266_back.bmp	./xpm/sprite_266_back.xpm 2>/dev/null
convert ./bmp/sprite_267_front.bmp	./xpm/sprite_267_front.xpm 2>/dev/null
convert ./bmp/sprite_267_back.bmp	./xpm/sprite_267_back.xpm 2>/dev/null
convert ./bmp/sprite_268_front.bmp	./xpm/sprite_268_front.xpm 2>/dev/null
convert ./bmp/sprite_268_back.bmp	./xpm/sprite_268_back.xpm 2>/dev/null
convert ./bmp/sprite_269_front.bmp	./xpm/sprite_269_front.xpm 2>/dev/null
convert ./bmp/sprite_269_back.bmp	./xpm/sprite_269_back.xpm 2>/dev/null
convert ./bmp/sprite_270_front.bmp	./xpm/sprite_270_front.xpm 2>/dev/null
convert ./bmp/sprite_270_back.bmp	./xpm/sprite_270_back.xpm 2>/dev/null
convert ./bmp/sprite_271_front.bmp	./xpm/sprite_271_front.xpm 2>/dev/null
convert ./bmp/sprite_271_back.bmp	./xpm/sprite_271_back.xpm 2>/dev/null
convert ./bmp/sprite_272_front.bmp	./xpm/sprite_272_front.xpm 2>/dev/null
convert ./bmp/sprite_272_back.bmp	./xpm/sprite_272_back.xpm 2>/dev/null
convert ./bmp/sprite_273_front.bmp	./xpm/sprite_273_front.xpm 2>/dev/null
convert ./bmp/sprite_273_back.bmp	./xpm/sprite_273_back.xpm 2>/dev/null
convert ./bmp/sprite_274_front.bmp	./xpm/sprite_274_front.xpm 2>/dev/null
convert ./bmp/sprite_274_back.bmp	./xpm/sprite_274_back.xpm 2>/dev/null
convert ./bmp/sprite_275_front.bmp	./xpm/sprite_275_front.xpm 2>/dev/null
convert ./bmp/sprite_275_back.bmp	./xpm/sprite_275_back.xpm 2>/dev/null
convert ./bmp/sprite_276_front.bmp	./xpm/sprite_276_front.xpm 2>/dev/null
convert ./bmp/sprite_276_back.bmp	./xpm/sprite_276_back.xpm 2>/dev/null
convert ./bmp/sprite_277_front.bmp	./xpm/sprite_277_front.xpm 2>/dev/null
convert ./bmp/sprite_277_back.bmp	./xpm/sprite_277_back.xpm 2>/dev/null
convert ./bmp/sprite_278_front.bmp	./xpm/sprite_278_front.xpm 2>/dev/null
convert ./bmp/sprite_278_back.bmp	./xpm/sprite_278_back.xpm 2>/dev/null
convert ./bmp/sprite_279_front.bmp	./xpm/sprite_279_front.xpm 2>/dev/null
convert ./bmp/sprite_279_back.bmp	./xpm/sprite_279_back.xpm 2>/dev/null
convert ./bmp/sprite_280_front.bmp	./xpm/sprite_280_front.xpm 2>/dev/null
convert ./bmp/sprite_280_back.bmp	./xpm/sprite_280_back.xpm 2>/dev/null
convert ./bmp/sprite_281_front.bmp	./xpm/sprite_281_front.xpm 2>/dev/null
convert ./bmp/sprite_281_back.bmp	./xpm/sprite_281_back.xpm 2>/dev/null
convert ./bmp/sprite_282_front.bmp	./xpm/sprite_282_front.xpm 2>/dev/null
convert ./bmp/sprite_282_back.bmp	./xpm/sprite_282_back.xpm 2>/dev/null
convert ./bmp/sprite_283_front.bmp	./xpm/sprite_283_front.xpm 2>/dev/null
convert ./bmp/sprite_283_back.bmp	./xpm/sprite_283_back.xpm 2>/dev/null
convert ./bmp/sprite_284_front.bmp	./xpm/sprite_284_front.xpm 2>/dev/null
convert ./bmp/sprite_284_back.bmp	./xpm/sprite_284_back.xpm 2>/dev/null
convert ./bmp/sprite_285_front.bmp	./xpm/sprite_285_front.xpm 2>/dev/null
convert ./bmp/sprite_285_back.bmp	./xpm/sprite_285_back.xpm 2>/dev/null
convert ./bmp/sprite_286_front.bmp	./xpm/sprite_286_front.xpm 2>/dev/null
convert ./bmp/sprite_286_back.bmp	./xpm/sprite_286_back.xpm 2>/dev/null
convert ./bmp/sprite_287_front.bmp	./xpm/sprite_287_front.xpm 2>/dev/null
convert ./bmp/sprite_287_back.bmp	./xpm/sprite_287_back.xpm 2>/dev/null
convert ./bmp/sprite_288_front.bmp	./xpm/sprite_288_front.xpm 2>/dev/null
convert ./bmp/sprite_288_back.bmp	./xpm/sprite_288_back.xpm 2>/dev/null
convert ./bmp/sprite_289_front.bmp	./xpm/sprite_289_front.xpm 2>/dev/null
convert ./bmp/sprite_289_back.bmp	./xpm/sprite_289_back.xpm 2>/dev/null
convert ./bmp/sprite_290_front.bmp	./xpm/sprite_290_front.xpm 2>/dev/null
convert ./bmp/sprite_290_back.bmp	./xpm/sprite_290_back.xpm 2>/dev/null
convert ./bmp/sprite_291_front.bmp	./xpm/sprite_291_front.xpm 2>/dev/null
convert ./bmp/sprite_291_back.bmp	./xpm/sprite_291_back.xpm 2>/dev/null
convert ./bmp/sprite_292_front.bmp	./xpm/sprite_292_front.xpm 2>/dev/null
convert ./bmp/sprite_292_back.bmp	./xpm/sprite_292_back.xpm 2>/dev/null
convert ./bmp/sprite_293_front.bmp	./xpm/sprite_293_front.xpm 2>/dev/null
convert ./bmp/sprite_293_back.bmp	./xpm/sprite_293_back.xpm 2>/dev/null
convert ./bmp/sprite_294_front.bmp	./xpm/sprite_294_front.xpm 2>/dev/null
convert ./bmp/sprite_294_back.bmp	./xpm/sprite_294_back.xpm 2>/dev/null
convert ./bmp/sprite_295_front.bmp	./xpm/sprite_295_front.xpm 2>/dev/null
convert ./bmp/sprite_295_back.bmp	./xpm/sprite_295_back.xpm 2>/dev/null
convert ./bmp/sprite_296_front.bmp	./xpm/sprite_296_front.xpm 2>/dev/null
convert ./bmp/sprite_296_back.bmp	./xpm/sprite_296_back.xpm 2>/dev/null
convert ./bmp/sprite_297_front.bmp	./xpm/sprite_297_front.xpm 2>/dev/null
convert ./bmp/sprite_297_back.bmp	./xpm/sprite_297_back.xpm 2>/dev/null
convert ./bmp/sprite_298_front.bmp	./xpm/sprite_298_front.xpm 2>/dev/null
convert ./bmp/sprite_298_back.bmp	./xpm/sprite_298_back.xpm 2>/dev/null
convert ./bmp/sprite_299_front.bmp	./xpm/sprite_299_front.xpm 2>/dev/null
convert ./bmp/sprite_299_back.bmp	./xpm/sprite_299_back.xpm 2>/dev/null
convert ./bmp/sprite_300_front.bmp	./xpm/sprite_300_front.xpm 2>/dev/null
convert ./bmp/sprite_300_back.bmp	./xpm/sprite_300_back.xpm 2>/dev/null
convert ./bmp/sprite_301_front.bmp	./xpm/sprite_301_front.xpm 2>/dev/null
convert ./bmp/sprite_301_back.bmp	./xpm/sprite_301_back.xpm 2>/dev/null
convert ./bmp/sprite_302_front.bmp	./xpm/sprite_302_front.xpm 2>/dev/null
convert ./bmp/sprite_302_back.bmp	./xpm/sprite_302_back.xpm 2>/dev/null
convert ./bmp/sprite_303_front.bmp	./xpm/sprite_303_front.xpm 2>/dev/null
convert ./bmp/sprite_303_back.bmp	./xpm/sprite_303_back.xpm 2>/dev/null
convert ./bmp/sprite_304_front.bmp	./xpm/sprite_304_front.xpm 2>/dev/null
convert ./bmp/sprite_304_back.bmp	./xpm/sprite_304_back.xpm 2>/dev/null
convert ./bmp/sprite_305_front.bmp	./xpm/sprite_305_front.xpm 2>/dev/null
convert ./bmp/sprite_305_back.bmp	./xpm/sprite_305_back.xpm 2>/dev/null
convert ./bmp/sprite_306_front.bmp	./xpm/sprite_306_front.xpm 2>/dev/null
convert ./bmp/sprite_306_back.bmp	./xpm/sprite_306_back.xpm 2>/dev/null
convert ./bmp/sprite_307_front.bmp	./xpm/sprite_307_front.xpm 2>/dev/null
convert ./bmp/sprite_307_back.bmp	./xpm/sprite_307_back.xpm 2>/dev/null
convert ./bmp/sprite_308_front.bmp	./xpm/sprite_308_front.xpm 2>/dev/null
convert ./bmp/sprite_308_back.bmp	./xpm/sprite_308_back.xpm 2>/dev/null
convert ./bmp/sprite_309_front.bmp	./xpm/sprite_309_front.xpm 2>/dev/null
convert ./bmp/sprite_309_back.bmp	./xpm/sprite_309_back.xpm 2>/dev/null
convert ./bmp/sprite_310_front.bmp	./xpm/sprite_310_front.xpm 2>/dev/null
convert ./bmp/sprite_310_back.bmp	./xpm/sprite_310_back.xpm 2>/dev/null
convert ./bmp/sprite_311_front.bmp	./xpm/sprite_311_front.xpm 2>/dev/null
convert ./bmp/sprite_311_back.bmp	./xpm/sprite_311_back.xpm 2>/dev/null
convert ./bmp/sprite_312_front.bmp	./xpm/sprite_312_front.xpm 2>/dev/null
convert ./bmp/sprite_312_back.bmp	./xpm/sprite_312_back.xpm 2>/dev/null
convert ./bmp/sprite_313_front.bmp	./xpm/sprite_313_front.xpm 2>/dev/null
convert ./bmp/sprite_313_back.bmp	./xpm/sprite_313_back.xpm 2>/dev/null
convert ./bmp/sprite_314_front.bmp	./xpm/sprite_314_front.xpm 2>/dev/null
convert ./bmp/sprite_314_back.bmp	./xpm/sprite_314_back.xpm 2>/dev/null
convert ./bmp/sprite_315_front.bmp	./xpm/sprite_315_front.xpm 2>/dev/null
convert ./bmp/sprite_315_back.bmp	./xpm/sprite_315_back.xpm 2>/dev/null
convert ./bmp/sprite_316_front.bmp	./xpm/sprite_316_front.xpm 2>/dev/null
convert ./bmp/sprite_316_back.bmp	./xpm/sprite_316_back.xpm 2>/dev/null
convert ./bmp/sprite_317_front.bmp	./xpm/sprite_317_front.xpm 2>/dev/null
convert ./bmp/sprite_317_back.bmp	./xpm/sprite_317_back.xpm 2>/dev/null
convert ./bmp/sprite_318_front.bmp	./xpm/sprite_318_front.xpm 2>/dev/null
convert ./bmp/sprite_318_back.bmp	./xpm/sprite_318_back.xpm 2>/dev/null
convert ./bmp/sprite_319_front.bmp	./xpm/sprite_319_front.xpm 2>/dev/null
convert ./bmp/sprite_319_back.bmp	./xpm/sprite_319_back.xpm 2>/dev/null
convert ./bmp/sprite_320_front.bmp	./xpm/sprite_320_front.xpm 2>/dev/null
convert ./bmp/sprite_320_back.bmp	./xpm/sprite_320_back.xpm 2>/dev/null
convert ./bmp/sprite_321_front.bmp	./xpm/sprite_321_front.xpm 2>/dev/null
convert ./bmp/sprite_321_back.bmp	./xpm/sprite_321_back.xpm 2>/dev/null
convert ./bmp/sprite_322_front.bmp	./xpm/sprite_322_front.xpm 2>/dev/null
convert ./bmp/sprite_322_back.bmp	./xpm/sprite_322_back.xpm 2>/dev/null
convert ./bmp/sprite_323_front.bmp	./xpm/sprite_323_front.xpm 2>/dev/null
convert ./bmp/sprite_323_back.bmp	./xpm/sprite_323_back.xpm 2>/dev/null
convert ./bmp/sprite_324_front.bmp	./xpm/sprite_324_front.xpm 2>/dev/null
convert ./bmp/sprite_324_back.bmp	./xpm/sprite_324_back.xpm 2>/dev/null
convert ./bmp/sprite_325_front.bmp	./xpm/sprite_325_front.xpm 2>/dev/null
convert ./bmp/sprite_325_back.bmp	./xpm/sprite_325_back.xpm 2>/dev/null
convert ./bmp/sprite_326_front.bmp	./xpm/sprite_326_front.xpm 2>/dev/null
convert ./bmp/sprite_326_back.bmp	./xpm/sprite_326_back.xpm 2>/dev/null
convert ./bmp/sprite_327_front.bmp	./xpm/sprite_327_front.xpm 2>/dev/null
convert ./bmp/sprite_327_back.bmp	./xpm/sprite_327_back.xpm 2>/dev/null
convert ./bmp/sprite_328_front.bmp	./xpm/sprite_328_front.xpm 2>/dev/null
convert ./bmp/sprite_328_back.bmp	./xpm/sprite_328_back.xpm 2>/dev/null
convert ./bmp/sprite_329_front.bmp	./xpm/sprite_329_front.xpm 2>/dev/null
convert ./bmp/sprite_329_back.bmp	./xpm/sprite_329_back.xpm 2>/dev/null
convert ./bmp/sprite_330_front.bmp	./xpm/sprite_330_front.xpm 2>/dev/null
convert ./bmp/sprite_330_back.bmp	./xpm/sprite_330_back.xpm 2>/dev/null
convert ./bmp/sprite_331_front.bmp	./xpm/sprite_331_front.xpm 2>/dev/null
convert ./bmp/sprite_331_back.bmp	./xpm/sprite_331_back.xpm 2>/dev/null
convert ./bmp/sprite_332_front.bmp	./xpm/sprite_332_front.xpm 2>/dev/null
convert ./bmp/sprite_332_back.bmp	./xpm/sprite_332_back.xpm 2>/dev/null
convert ./bmp/sprite_333_front.bmp	./xpm/sprite_333_front.xpm 2>/dev/null
convert ./bmp/sprite_333_back.bmp	./xpm/sprite_333_back.xpm 2>/dev/null
convert ./bmp/sprite_334_front.bmp	./xpm/sprite_334_front.xpm 2>/dev/null
convert ./bmp/sprite_334_back.bmp	./xpm/sprite_334_back.xpm 2>/dev/null
convert ./bmp/sprite_335_front.bmp	./xpm/sprite_335_front.xpm 2>/dev/null
convert ./bmp/sprite_335_back.bmp	./xpm/sprite_335_back.xpm 2>/dev/null
convert ./bmp/sprite_336_front.bmp	./xpm/sprite_336_front.xpm 2>/dev/null
convert ./bmp/sprite_336_back.bmp	./xpm/sprite_336_back.xpm 2>/dev/null
convert ./bmp/sprite_337_front.bmp	./xpm/sprite_337_front.xpm 2>/dev/null
convert ./bmp/sprite_337_back.bmp	./xpm/sprite_337_back.xpm 2>/dev/null
convert ./bmp/sprite_338_front.bmp	./xpm/sprite_338_front.xpm 2>/dev/null
convert ./bmp/sprite_338_back.bmp	./xpm/sprite_338_back.xpm 2>/dev/null
convert ./bmp/sprite_339_front.bmp	./xpm/sprite_339_front.xpm 2>/dev/null
convert ./bmp/sprite_339_back.bmp	./xpm/sprite_339_back.xpm 2>/dev/null
convert ./bmp/sprite_340_front.bmp	./xpm/sprite_340_front.xpm 2>/dev/null
convert ./bmp/sprite_340_back.bmp	./xpm/sprite_340_back.xpm 2>/dev/null
convert ./bmp/sprite_341_front.bmp	./xpm/sprite_341_front.xpm 2>/dev/null
convert ./bmp/sprite_341_back.bmp	./xpm/sprite_341_back.xpm 2>/dev/null
convert ./bmp/sprite_342_front.bmp	./xpm/sprite_342_front.xpm 2>/dev/null
convert ./bmp/sprite_342_back.bmp	./xpm/sprite_342_back.xpm 2>/dev/null
convert ./bmp/sprite_343_front.bmp	./xpm/sprite_343_front.xpm 2>/dev/null
convert ./bmp/sprite_343_back.bmp	./xpm/sprite_343_back.xpm 2>/dev/null
convert ./bmp/sprite_344_front.bmp	./xpm/sprite_344_front.xpm 2>/dev/null
convert ./bmp/sprite_344_back.bmp	./xpm/sprite_344_back.xpm 2>/dev/null
convert ./bmp/sprite_345_front.bmp	./xpm/sprite_345_front.xpm 2>/dev/null
convert ./bmp/sprite_345_back.bmp	./xpm/sprite_345_back.xpm 2>/dev/null
convert ./bmp/sprite_346_front.bmp	./xpm/sprite_346_front.xpm 2>/dev/null
convert ./bmp/sprite_346_back.bmp	./xpm/sprite_346_back.xpm 2>/dev/null
convert ./bmp/sprite_347_front.bmp	./xpm/sprite_347_front.xpm 2>/dev/null
convert ./bmp/sprite_347_back.bmp	./xpm/sprite_347_back.xpm 2>/dev/null
convert ./bmp/sprite_348_front.bmp	./xpm/sprite_348_front.xpm 2>/dev/null
convert ./bmp/sprite_348_back.bmp	./xpm/sprite_348_back.xpm 2>/dev/null
convert ./bmp/sprite_349_front.bmp	./xpm/sprite_349_front.xpm 2>/dev/null
convert ./bmp/sprite_349_back.bmp	./xpm/sprite_349_back.xpm 2>/dev/null
convert ./bmp/sprite_350_front.bmp	./xpm/sprite_350_front.xpm 2>/dev/null
convert ./bmp/sprite_350_back.bmp	./xpm/sprite_350_back.xpm 2>/dev/null
convert ./bmp/sprite_351_front.bmp	./xpm/sprite_351_front.xpm 2>/dev/null
convert ./bmp/sprite_351_back.bmp	./xpm/sprite_351_back.xpm 2>/dev/null
convert ./bmp/sprite_352_front.bmp	./xpm/sprite_352_front.xpm 2>/dev/null
convert ./bmp/sprite_352_back.bmp	./xpm/sprite_352_back.xpm 2>/dev/null
convert ./bmp/sprite_353_front.bmp	./xpm/sprite_353_front.xpm 2>/dev/null
convert ./bmp/sprite_353_back.bmp	./xpm/sprite_353_back.xpm 2>/dev/null
convert ./bmp/sprite_354_front.bmp	./xpm/sprite_354_front.xpm 2>/dev/null
convert ./bmp/sprite_354_back.bmp	./xpm/sprite_354_back.xpm 2>/dev/null
convert ./bmp/sprite_355_front.bmp	./xpm/sprite_355_front.xpm 2>/dev/null
convert ./bmp/sprite_355_back.bmp	./xpm/sprite_355_back.xpm 2>/dev/null
convert ./bmp/sprite_356_front.bmp	./xpm/sprite_356_front.xpm 2>/dev/null
convert ./bmp/sprite_356_back.bmp	./xpm/sprite_356_back.xpm 2>/dev/null
convert ./bmp/sprite_357_front.bmp	./xpm/sprite_357_front.xpm 2>/dev/null
convert ./bmp/sprite_357_back.bmp	./xpm/sprite_357_back.xpm 2>/dev/null
convert ./bmp/sprite_358_front.bmp	./xpm/sprite_358_front.xpm 2>/dev/null
convert ./bmp/sprite_358_back.bmp	./xpm/sprite_358_back.xpm 2>/dev/null
convert ./bmp/sprite_359_front.bmp	./xpm/sprite_359_front.xpm 2>/dev/null
convert ./bmp/sprite_359_back.bmp	./xpm/sprite_359_back.xpm 2>/dev/null
convert ./bmp/sprite_360_front.bmp	./xpm/sprite_360_front.xpm 2>/dev/null
convert ./bmp/sprite_360_back.bmp	./xpm/sprite_360_back.xpm 2>/dev/null
convert ./bmp/sprite_361_front.bmp	./xpm/sprite_361_front.xpm 2>/dev/null
convert ./bmp/sprite_361_back.bmp	./xpm/sprite_361_back.xpm 2>/dev/null
convert ./bmp/sprite_362_front.bmp	./xpm/sprite_362_front.xpm 2>/dev/null
convert ./bmp/sprite_362_back.bmp	./xpm/sprite_362_back.xpm 2>/dev/null
convert ./bmp/sprite_363_front.bmp	./xpm/sprite_363_front.xpm 2>/dev/null
convert ./bmp/sprite_363_back.bmp	./xpm/sprite_363_back.xpm 2>/dev/null
convert ./bmp/sprite_364_front.bmp	./xpm/sprite_364_front.xpm 2>/dev/null
convert ./bmp/sprite_364_back.bmp	./xpm/sprite_364_back.xpm 2>/dev/null
convert ./bmp/sprite_365_front.bmp	./xpm/sprite_365_front.xpm 2>/dev/null
convert ./bmp/sprite_365_back.bmp	./xpm/sprite_365_back.xpm 2>/dev/null
convert ./bmp/sprite_366_front.bmp	./xpm/sprite_366_front.xpm 2>/dev/null
convert ./bmp/sprite_366_back.bmp	./xpm/sprite_366_back.xpm 2>/dev/null
convert ./bmp/sprite_367_front.bmp	./xpm/sprite_367_front.xpm 2>/dev/null
convert ./bmp/sprite_367_back.bmp	./xpm/sprite_367_back.xpm 2>/dev/null
convert ./bmp/sprite_368_front.bmp	./xpm/sprite_368_front.xpm 2>/dev/null
convert ./bmp/sprite_368_back.bmp	./xpm/sprite_368_back.xpm 2>/dev/null
convert ./bmp/sprite_369_front.bmp	./xpm/sprite_369_front.xpm 2>/dev/null
convert ./bmp/sprite_369_back.bmp	./xpm/sprite_369_back.xpm 2>/dev/null
convert ./bmp/sprite_370_front.bmp	./xpm/sprite_370_front.xpm 2>/dev/null
convert ./bmp/sprite_370_back.bmp	./xpm/sprite_370_back.xpm 2>/dev/null
convert ./bmp/sprite_371_front.bmp	./xpm/sprite_371_front.xpm 2>/dev/null
convert ./bmp/sprite_371_back.bmp	./xpm/sprite_371_back.xpm 2>/dev/null
convert ./bmp/sprite_372_front.bmp	./xpm/sprite_372_front.xpm 2>/dev/null
convert ./bmp/sprite_372_back.bmp	./xpm/sprite_372_back.xpm 2>/dev/null
convert ./bmp/sprite_373_front.bmp	./xpm/sprite_373_front.xpm 2>/dev/null
convert ./bmp/sprite_373_back.bmp	./xpm/sprite_373_back.xpm 2>/dev/null
convert ./bmp/sprite_374_front.bmp	./xpm/sprite_374_front.xpm 2>/dev/null
convert ./bmp/sprite_374_back.bmp	./xpm/sprite_374_back.xpm 2>/dev/null
convert ./bmp/sprite_375_front.bmp	./xpm/sprite_375_front.xpm 2>/dev/null
convert ./bmp/sprite_375_back.bmp	./xpm/sprite_375_back.xpm 2>/dev/null
convert ./bmp/sprite_376_front.bmp	./xpm/sprite_376_front.xpm 2>/dev/null
convert ./bmp/sprite_376_back.bmp	./xpm/sprite_376_back.xpm 2>/dev/null
convert ./bmp/sprite_377_front.bmp	./xpm/sprite_377_front.xpm 2>/dev/null
convert ./bmp/sprite_377_back.bmp	./xpm/sprite_377_back.xpm 2>/dev/null
convert ./bmp/sprite_378_front.bmp	./xpm/sprite_378_front.xpm 2>/dev/null
convert ./bmp/sprite_378_back.bmp	./xpm/sprite_378_back.xpm 2>/dev/null
convert ./bmp/sprite_379_front.bmp	./xpm/sprite_379_front.xpm 2>/dev/null
convert ./bmp/sprite_379_back.bmp	./xpm/sprite_379_back.xpm 2>/dev/null
convert ./bmp/sprite_380_front.bmp	./xpm/sprite_380_front.xpm 2>/dev/null
convert ./bmp/sprite_380_back.bmp	./xpm/sprite_380_back.xpm 2>/dev/null
convert ./bmp/sprite_381_front.bmp	./xpm/sprite_381_front.xpm 2>/dev/null
convert ./bmp/sprite_381_back.bmp	./xpm/sprite_381_back.xpm 2>/dev/null
convert ./bmp/sprite_382_front.bmp	./xpm/sprite_382_front.xpm 2>/dev/null
convert ./bmp/sprite_382_back.bmp	./xpm/sprite_382_back.xpm 2>/dev/null
convert ./bmp/sprite_383_front.bmp	./xpm/sprite_383_front.xpm 2>/dev/null
convert ./bmp/sprite_383_back.bmp	./xpm/sprite_383_back.xpm 2>/dev/null
convert ./bmp/sprite_384_front.bmp	./xpm/sprite_384_front.xpm 2>/dev/null
convert ./bmp/sprite_384_back.bmp	./xpm/sprite_384_back.xpm 2>/dev/null
convert ./bmp/sprite_385_front.bmp	./xpm/sprite_385_front.xpm 2>/dev/null
convert ./bmp/sprite_385_back.bmp	./xpm/sprite_385_back.xpm 2>/dev/null
convert ./bmp/sprite_386_front.bmp	./xpm/sprite_386_front.xpm 2>/dev/null
convert ./bmp/sprite_386_back.bmp	./xpm/sprite_386_back.xpm 2>/dev/null
convert ./bmp/sprite_387_front.bmp	./xpm/sprite_387_front.xpm 2>/dev/null
convert ./bmp/sprite_387_back.bmp	./xpm/sprite_387_back.xpm 2>/dev/null
convert ./bmp/sprite_388_front.bmp	./xpm/sprite_388_front.xpm 2>/dev/null
convert ./bmp/sprite_388_back.bmp	./xpm/sprite_388_back.xpm 2>/dev/null
convert ./bmp/sprite_389_front.bmp	./xpm/sprite_389_front.xpm 2>/dev/null
convert ./bmp/sprite_389_back.bmp	./xpm/sprite_389_back.xpm 2>/dev/null
convert ./bmp/sprite_390_front.bmp	./xpm/sprite_390_front.xpm 2>/dev/null
convert ./bmp/sprite_390_back.bmp	./xpm/sprite_390_back.xpm 2>/dev/null
convert ./bmp/sprite_391_front.bmp	./xpm/sprite_391_front.xpm 2>/dev/null
convert ./bmp/sprite_391_back.bmp	./xpm/sprite_391_back.xpm 2>/dev/null
convert ./bmp/sprite_392_front.bmp	./xpm/sprite_392_front.xpm 2>/dev/null
convert ./bmp/sprite_392_back.bmp	./xpm/sprite_392_back.xpm 2>/dev/null
convert ./bmp/sprite_393_front.bmp	./xpm/sprite_393_front.xpm 2>/dev/null
convert ./bmp/sprite_393_back.bmp	./xpm/sprite_393_back.xpm 2>/dev/null
convert ./bmp/sprite_394_front.bmp	./xpm/sprite_394_front.xpm 2>/dev/null
convert ./bmp/sprite_394_back.bmp	./xpm/sprite_394_back.xpm 2>/dev/null
convert ./bmp/sprite_395_front.bmp	./xpm/sprite_395_front.xpm 2>/dev/null
convert ./bmp/sprite_395_back.bmp	./xpm/sprite_395_back.xpm 2>/dev/null
convert ./bmp/sprite_396_front.bmp	./xpm/sprite_396_front.xpm 2>/dev/null
convert ./bmp/sprite_396_back.bmp	./xpm/sprite_396_back.xpm 2>/dev/null
convert ./bmp/sprite_397_front.bmp	./xpm/sprite_397_front.xpm 2>/dev/null
convert ./bmp/sprite_397_back.bmp	./xpm/sprite_397_back.xpm 2>/dev/null
convert ./bmp/sprite_398_front.bmp	./xpm/sprite_398_front.xpm 2>/dev/null
convert ./bmp/sprite_398_back.bmp	./xpm/sprite_398_back.xpm 2>/dev/null
convert ./bmp/sprite_399_front.bmp	./xpm/sprite_399_front.xpm 2>/dev/null
convert ./bmp/sprite_399_back.bmp	./xpm/sprite_399_back.xpm 2>/dev/null
convert ./bmp/sprite_400_front.bmp	./xpm/sprite_400_front.xpm 2>/dev/null
convert ./bmp/sprite_400_back.bmp	./xpm/sprite_400_back.xpm 2>/dev/null
convert ./bmp/sprite_401_front.bmp	./xpm/sprite_401_front.xpm 2>/dev/null
convert ./bmp/sprite_401_back.bmp	./xpm/sprite_401_back.xpm 2>/dev/null
convert ./bmp/sprite_402_front.bmp	./xpm/sprite_402_front.xpm 2>/dev/null
convert ./bmp/sprite_402_back.bmp	./xpm/sprite_402_back.xpm 2>/dev/null
convert ./bmp/sprite_403_front.bmp	./xpm/sprite_403_front.xpm 2>/dev/null
convert ./bmp/sprite_403_back.bmp	./xpm/sprite_403_back.xpm 2>/dev/null
convert ./bmp/sprite_404_front.bmp	./xpm/sprite_404_front.xpm 2>/dev/null
convert ./bmp/sprite_404_back.bmp	./xpm/sprite_404_back.xpm 2>/dev/null
convert ./bmp/sprite_405_front.bmp	./xpm/sprite_405_front.xpm 2>/dev/null
convert ./bmp/sprite_405_back.bmp	./xpm/sprite_405_back.xpm 2>/dev/null
convert ./bmp/sprite_406_front.bmp	./xpm/sprite_406_front.xpm 2>/dev/null
convert ./bmp/sprite_406_back.bmp	./xpm/sprite_406_back.xpm 2>/dev/null
convert ./bmp/sprite_407_front.bmp	./xpm/sprite_407_front.xpm 2>/dev/null
convert ./bmp/sprite_407_back.bmp	./xpm/sprite_407_back.xpm 2>/dev/null
convert ./bmp/sprite_408_front.bmp	./xpm/sprite_408_front.xpm 2>/dev/null
convert ./bmp/sprite_408_back.bmp	./xpm/sprite_408_back.xpm 2>/dev/null
convert ./bmp/sprite_409_front.bmp	./xpm/sprite_409_front.xpm 2>/dev/null
convert ./bmp/sprite_409_back.bmp	./xpm/sprite_409_back.xpm 2>/dev/null
convert ./bmp/sprite_410_front.bmp	./xpm/sprite_410_front.xpm 2>/dev/null
convert ./bmp/sprite_410_back.bmp	./xpm/sprite_410_back.xpm 2>/dev/null
convert ./bmp/sprite_411_front.bmp	./xpm/sprite_411_front.xpm 2>/dev/null
convert ./bmp/sprite_411_back.bmp	./xpm/sprite_411_back.xpm 2>/dev/null
convert ./bmp/sprite_412_front.bmp	./xpm/sprite_412_front.xpm 2>/dev/null
convert ./bmp/sprite_412_back.bmp	./xpm/sprite_412_back.xpm 2>/dev/null
convert ./bmp/sprite_413_front.bmp	./xpm/sprite_413_front.xpm 2>/dev/null
convert ./bmp/sprite_413_back.bmp	./xpm/sprite_413_back.xpm 2>/dev/null
convert ./bmp/sprite_414_front.bmp	./xpm/sprite_414_front.xpm 2>/dev/null
convert ./bmp/sprite_414_back.bmp	./xpm/sprite_414_back.xpm 2>/dev/null
convert ./bmp/sprite_415_front.bmp	./xpm/sprite_415_front.xpm 2>/dev/null
convert ./bmp/sprite_415_back.bmp	./xpm/sprite_415_back.xpm 2>/dev/null
convert ./bmp/sprite_416_front.bmp	./xpm/sprite_416_front.xpm 2>/dev/null
convert ./bmp/sprite_416_back.bmp	./xpm/sprite_416_back.xpm 2>/dev/null
convert ./bmp/sprite_417_front.bmp	./xpm/sprite_417_front.xpm 2>/dev/null
convert ./bmp/sprite_417_back.bmp	./xpm/sprite_417_back.xpm 2>/dev/null
convert ./bmp/sprite_418_front.bmp	./xpm/sprite_418_front.xpm 2>/dev/null
convert ./bmp/sprite_418_back.bmp	./xpm/sprite_418_back.xpm 2>/dev/null
convert ./bmp/sprite_419_front.bmp	./xpm/sprite_419_front.xpm 2>/dev/null
convert ./bmp/sprite_419_back.bmp	./xpm/sprite_419_back.xpm 2>/dev/null
convert ./bmp/sprite_420_front.bmp	./xpm/sprite_420_front.xpm 2>/dev/null
convert ./bmp/sprite_420_back.bmp	./xpm/sprite_420_back.xpm 2>/dev/null
convert ./bmp/sprite_421_front.bmp	./xpm/sprite_421_front.xpm 2>/dev/null
convert ./bmp/sprite_421_back.bmp	./xpm/sprite_421_back.xpm 2>/dev/null
convert ./bmp/sprite_422_front.bmp	./xpm/sprite_422_front.xpm 2>/dev/null
convert ./bmp/sprite_422_back.bmp	./xpm/sprite_422_back.xpm 2>/dev/null
convert ./bmp/sprite_423_front.bmp	./xpm/sprite_423_front.xpm 2>/dev/null
convert ./bmp/sprite_423_back.bmp	./xpm/sprite_423_back.xpm 2>/dev/null
convert ./bmp/sprite_424_front.bmp	./xpm/sprite_424_front.xpm 2>/dev/null
convert ./bmp/sprite_424_back.bmp	./xpm/sprite_424_back.xpm 2>/dev/null
convert ./bmp/sprite_425_front.bmp	./xpm/sprite_425_front.xpm 2>/dev/null
convert ./bmp/sprite_425_back.bmp	./xpm/sprite_425_back.xpm 2>/dev/null
convert ./bmp/sprite_426_front.bmp	./xpm/sprite_426_front.xpm 2>/dev/null
convert ./bmp/sprite_426_back.bmp	./xpm/sprite_426_back.xpm 2>/dev/null
convert ./bmp/sprite_427_front.bmp	./xpm/sprite_427_front.xpm 2>/dev/null
convert ./bmp/sprite_427_back.bmp	./xpm/sprite_427_back.xpm 2>/dev/null
convert ./bmp/sprite_428_front.bmp	./xpm/sprite_428_front.xpm 2>/dev/null
convert ./bmp/sprite_428_back.bmp	./xpm/sprite_428_back.xpm 2>/dev/null
convert ./bmp/sprite_429_front.bmp	./xpm/sprite_429_front.xpm 2>/dev/null
convert ./bmp/sprite_429_back.bmp	./xpm/sprite_429_back.xpm 2>/dev/null
convert ./bmp/sprite_430_front.bmp	./xpm/sprite_430_front.xpm 2>/dev/null
convert ./bmp/sprite_430_back.bmp	./xpm/sprite_430_back.xpm 2>/dev/null
convert ./bmp/sprite_431_front.bmp	./xpm/sprite_431_front.xpm 2>/dev/null
convert ./bmp/sprite_431_back.bmp	./xpm/sprite_431_back.xpm 2>/dev/null
convert ./bmp/sprite_432_front.bmp	./xpm/sprite_432_front.xpm 2>/dev/null
convert ./bmp/sprite_432_back.bmp	./xpm/sprite_432_back.xpm 2>/dev/null
convert ./bmp/sprite_433_front.bmp	./xpm/sprite_433_front.xpm 2>/dev/null
convert ./bmp/sprite_433_back.bmp	./xpm/sprite_433_back.xpm 2>/dev/null
convert ./bmp/sprite_434_front.bmp	./xpm/sprite_434_front.xpm 2>/dev/null
convert ./bmp/sprite_434_back.bmp	./xpm/sprite_434_back.xpm 2>/dev/null
convert ./bmp/sprite_435_front.bmp	./xpm/sprite_435_front.xpm 2>/dev/null
convert ./bmp/sprite_435_back.bmp	./xpm/sprite_435_back.xpm 2>/dev/null
convert ./bmp/sprite_436_front.bmp	./xpm/sprite_436_front.xpm 2>/dev/null
convert ./bmp/sprite_436_back.bmp	./xpm/sprite_436_back.xpm 2>/dev/null
convert ./bmp/sprite_437_front.bmp	./xpm/sprite_437_front.xpm 2>/dev/null
convert ./bmp/sprite_437_back.bmp	./xpm/sprite_437_back.xpm 2>/dev/null
convert ./bmp/sprite_438_front.bmp	./xpm/sprite_438_front.xpm 2>/dev/null
convert ./bmp/sprite_438_back.bmp	./xpm/sprite_438_back.xpm 2>/dev/null
convert ./bmp/sprite_439_front.bmp	./xpm/sprite_439_front.xpm 2>/dev/null
convert ./bmp/sprite_439_back.bmp	./xpm/sprite_439_back.xpm 2>/dev/null
convert ./bmp/sprite_440_front.bmp	./xpm/sprite_440_front.xpm 2>/dev/null
convert ./bmp/sprite_440_back.bmp	./xpm/sprite_440_back.xpm 2>/dev/null
convert ./bmp/sprite_441_front.bmp	./xpm/sprite_441_front.xpm 2>/dev/null
convert ./bmp/sprite_441_back.bmp	./xpm/sprite_441_back.xpm 2>/dev/null
convert ./bmp/sprite_442_front.bmp	./xpm/sprite_442_front.xpm 2>/dev/null
convert ./bmp/sprite_442_back.bmp	./xpm/sprite_442_back.xpm 2>/dev/null
convert ./bmp/sprite_443_front.bmp	./xpm/sprite_443_front.xpm 2>/dev/null
convert ./bmp/sprite_443_back.bmp	./xpm/sprite_443_back.xpm 2>/dev/null
convert ./bmp/sprite_444_front.bmp	./xpm/sprite_444_front.xpm 2>/dev/null
convert ./bmp/sprite_444_back.bmp	./xpm/sprite_444_back.xpm 2>/dev/null
convert ./bmp/sprite_445_front.bmp	./xpm/sprite_445_front.xpm 2>/dev/null
convert ./bmp/sprite_445_back.bmp	./xpm/sprite_445_back.xpm 2>/dev/null
convert ./bmp/sprite_446_front.bmp	./xpm/sprite_446_front.xpm 2>/dev/null
convert ./bmp/sprite_446_back.bmp	./xpm/sprite_446_back.xpm 2>/dev/null
convert ./bmp/sprite_447_front.bmp	./xpm/sprite_447_front.xpm 2>/dev/null
convert ./bmp/sprite_447_back.bmp	./xpm/sprite_447_back.xpm 2>/dev/null
convert ./bmp/sprite_448_front.bmp	./xpm/sprite_448_front.xpm 2>/dev/null
convert ./bmp/sprite_448_back.bmp	./xpm/sprite_448_back.xpm 2>/dev/null
convert ./bmp/sprite_449_front.bmp	./xpm/sprite_449_front.xpm 2>/dev/null
convert ./bmp/sprite_449_back.bmp	./xpm/sprite_449_back.xpm 2>/dev/null
convert ./bmp/sprite_450_front.bmp	./xpm/sprite_450_front.xpm 2>/dev/null
convert ./bmp/sprite_450_back.bmp	./xpm/sprite_450_back.xpm 2>/dev/null
convert ./bmp/sprite_451_front.bmp	./xpm/sprite_451_front.xpm 2>/dev/null
convert ./bmp/sprite_451_back.bmp	./xpm/sprite_451_back.xpm 2>/dev/null
convert ./bmp/sprite_452_front.bmp	./xpm/sprite_452_front.xpm 2>/dev/null
convert ./bmp/sprite_452_back.bmp	./xpm/sprite_452_back.xpm 2>/dev/null
convert ./bmp/sprite_453_front.bmp	./xpm/sprite_453_front.xpm 2>/dev/null
convert ./bmp/sprite_453_back.bmp	./xpm/sprite_453_back.xpm 2>/dev/null
convert ./bmp/sprite_454_front.bmp	./xpm/sprite_454_front.xpm 2>/dev/null
convert ./bmp/sprite_454_back.bmp	./xpm/sprite_454_back.xpm 2>/dev/null
convert ./bmp/sprite_455_front.bmp	./xpm/sprite_455_front.xpm 2>/dev/null
convert ./bmp/sprite_455_back.bmp	./xpm/sprite_455_back.xpm 2>/dev/null
convert ./bmp/sprite_456_front.bmp	./xpm/sprite_456_front.xpm 2>/dev/null
convert ./bmp/sprite_456_back.bmp	./xpm/sprite_456_back.xpm 2>/dev/null
convert ./bmp/sprite_457_front.bmp	./xpm/sprite_457_front.xpm 2>/dev/null
convert ./bmp/sprite_457_back.bmp	./xpm/sprite_457_back.xpm 2>/dev/null
convert ./bmp/sprite_458_front.bmp	./xpm/sprite_458_front.xpm 2>/dev/null
convert ./bmp/sprite_458_back.bmp	./xpm/sprite_458_back.xpm 2>/dev/null
convert ./bmp/sprite_459_front.bmp	./xpm/sprite_459_front.xpm 2>/dev/null
convert ./bmp/sprite_459_back.bmp	./xpm/sprite_459_back.xpm 2>/dev/null
convert ./bmp/sprite_460_front.bmp	./xpm/sprite_460_front.xpm 2>/dev/null
convert ./bmp/sprite_460_back.bmp	./xpm/sprite_460_back.xpm 2>/dev/null
convert ./bmp/sprite_461_front.bmp	./xpm/sprite_461_front.xpm 2>/dev/null
convert ./bmp/sprite_461_back.bmp	./xpm/sprite_461_back.xpm 2>/dev/null
convert ./bmp/sprite_462_front.bmp	./xpm/sprite_462_front.xpm 2>/dev/null
convert ./bmp/sprite_462_back.bmp	./xpm/sprite_462_back.xpm 2>/dev/null
convert ./bmp/sprite_463_front.bmp	./xpm/sprite_463_front.xpm 2>/dev/null
convert ./bmp/sprite_463_back.bmp	./xpm/sprite_463_back.xpm 2>/dev/null
convert ./bmp/sprite_464_front.bmp	./xpm/sprite_464_front.xpm 2>/dev/null
convert ./bmp/sprite_464_back.bmp	./xpm/sprite_464_back.xpm 2>/dev/null
convert ./bmp/sprite_465_front.bmp	./xpm/sprite_465_front.xpm 2>/dev/null
convert ./bmp/sprite_465_back.bmp	./xpm/sprite_465_back.xpm 2>/dev/null
convert ./bmp/sprite_466_front.bmp	./xpm/sprite_466_front.xpm 2>/dev/null
convert ./bmp/sprite_466_back.bmp	./xpm/sprite_466_back.xpm 2>/dev/null
convert ./bmp/sprite_467_front.bmp	./xpm/sprite_467_front.xpm 2>/dev/null
convert ./bmp/sprite_467_back.bmp	./xpm/sprite_467_back.xpm 2>/dev/null
convert ./bmp/sprite_468_front.bmp	./xpm/sprite_468_front.xpm 2>/dev/null
convert ./bmp/sprite_468_back.bmp	./xpm/sprite_468_back.xpm 2>/dev/null
convert ./bmp/sprite_469_front.bmp	./xpm/sprite_469_front.xpm 2>/dev/null
convert ./bmp/sprite_469_back.bmp	./xpm/sprite_469_back.xpm 2>/dev/null
convert ./bmp/sprite_470_front.bmp	./xpm/sprite_470_front.xpm 2>/dev/null
convert ./bmp/sprite_470_back.bmp	./xpm/sprite_470_back.xpm 2>/dev/null
convert ./bmp/sprite_471_front.bmp	./xpm/sprite_471_front.xpm 2>/dev/null
convert ./bmp/sprite_471_back.bmp	./xpm/sprite_471_back.xpm 2>/dev/null
convert ./bmp/sprite_472_front.bmp	./xpm/sprite_472_front.xpm 2>/dev/null
convert ./bmp/sprite_472_back.bmp	./xpm/sprite_472_back.xpm 2>/dev/null
convert ./bmp/sprite_473_front.bmp	./xpm/sprite_473_front.xpm 2>/dev/null
convert ./bmp/sprite_473_back.bmp	./xpm/sprite_473_back.xpm 2>/dev/null
convert ./bmp/sprite_474_front.bmp	./xpm/sprite_474_front.xpm 2>/dev/null
convert ./bmp/sprite_474_back.bmp	./xpm/sprite_474_back.xpm 2>/dev/null
convert ./bmp/sprite_475_front.bmp	./xpm/sprite_475_front.xpm 2>/dev/null
convert ./bmp/sprite_475_back.bmp	./xpm/sprite_475_back.xpm 2>/dev/null
convert ./bmp/sprite_476_front.bmp	./xpm/sprite_476_front.xpm 2>/dev/null
convert ./bmp/sprite_476_back.bmp	./xpm/sprite_476_back.xpm 2>/dev/null
convert ./bmp/sprite_477_front.bmp	./xpm/sprite_477_front.xpm 2>/dev/null
convert ./bmp/sprite_477_back.bmp	./xpm/sprite_477_back.xpm 2>/dev/null
convert ./bmp/sprite_478_front.bmp	./xpm/sprite_478_front.xpm 2>/dev/null
convert ./bmp/sprite_478_back.bmp	./xpm/sprite_478_back.xpm 2>/dev/null
convert ./bmp/sprite_479_front.bmp	./xpm/sprite_479_front.xpm 2>/dev/null
convert ./bmp/sprite_479_back.bmp	./xpm/sprite_479_back.xpm 2>/dev/null
convert ./bmp/sprite_480_front.bmp	./xpm/sprite_480_front.xpm 2>/dev/null
convert ./bmp/sprite_480_back.bmp	./xpm/sprite_480_back.xpm 2>/dev/null
convert ./bmp/sprite_481_front.bmp	./xpm/sprite_481_front.xpm 2>/dev/null
convert ./bmp/sprite_481_back.bmp	./xpm/sprite_481_back.xpm 2>/dev/null
convert ./bmp/sprite_482_front.bmp	./xpm/sprite_482_front.xpm 2>/dev/null
convert ./bmp/sprite_482_back.bmp	./xpm/sprite_482_back.xpm 2>/dev/null
convert ./bmp/sprite_483_front.bmp	./xpm/sprite_483_front.xpm 2>/dev/null
convert ./bmp/sprite_483_back.bmp	./xpm/sprite_483_back.xpm 2>/dev/null
convert ./bmp/sprite_484_front.bmp	./xpm/sprite_484_front.xpm 2>/dev/null
convert ./bmp/sprite_484_back.bmp	./xpm/sprite_484_back.xpm 2>/dev/null
convert ./bmp/sprite_485_front.bmp	./xpm/sprite_485_front.xpm 2>/dev/null
convert ./bmp/sprite_485_back.bmp	./xpm/sprite_485_back.xpm 2>/dev/null
convert ./bmp/sprite_486_front.bmp	./xpm/sprite_486_front.xpm 2>/dev/null
convert ./bmp/sprite_486_back.bmp	./xpm/sprite_486_back.xpm 2>/dev/null
convert ./bmp/sprite_487_front.bmp	./xpm/sprite_487_front.xpm 2>/dev/null
convert ./bmp/sprite_487_back.bmp	./xpm/sprite_487_back.xpm 2>/dev/null
convert ./bmp/sprite_488_front.bmp	./xpm/sprite_488_front.xpm 2>/dev/null
convert ./bmp/sprite_488_back.bmp	./xpm/sprite_488_back.xpm 2>/dev/null
convert ./bmp/sprite_489_front.bmp	./xpm/sprite_489_front.xpm 2>/dev/null
convert ./bmp/sprite_489_back.bmp	./xpm/sprite_489_back.xpm 2>/dev/null
convert ./bmp/sprite_490_front.bmp	./xpm/sprite_490_front.xpm 2>/dev/null
convert ./bmp/sprite_490_back.bmp	./xpm/sprite_490_back.xpm 2>/dev/null
convert ./bmp/sprite_491_front.bmp	./xpm/sprite_491_front.xpm 2>/dev/null
convert ./bmp/sprite_491_back.bmp	./xpm/sprite_491_back.xpm 2>/dev/null
convert ./bmp/sprite_492_front.bmp	./xpm/sprite_492_front.xpm 2>/dev/null
convert ./bmp/sprite_492_back.bmp	./xpm/sprite_492_back.xpm 2>/dev/null
convert ./bmp/sprite_493_front.bmp	./xpm/sprite_493_front.xpm 2>/dev/null
convert ./bmp/sprite_493_back.bmp	./xpm/sprite_493_back.xpm 2>/dev/null
convert ./bmp/sprite_494_front.bmp	./xpm/sprite_494_front.xpm 2>/dev/null
convert ./bmp/sprite_494_back.bmp	./xpm/sprite_494_back.xpm 2>/dev/null
convert ./bmp/sprite_495_front.bmp	./xpm/sprite_495_front.xpm 2>/dev/null
convert ./bmp/sprite_495_back.bmp	./xpm/sprite_495_back.xpm 2>/dev/null
convert ./bmp/sprite_496_front.bmp	./xpm/sprite_496_front.xpm 2>/dev/null
convert ./bmp/sprite_496_back.bmp	./xpm/sprite_496_back.xpm 2>/dev/null
convert ./bmp/sprite_497_front.bmp	./xpm/sprite_497_front.xpm 2>/dev/null
convert ./bmp/sprite_497_back.bmp	./xpm/sprite_497_back.xpm 2>/dev/null
convert ./bmp/sprite_498_front.bmp	./xpm/sprite_498_front.xpm 2>/dev/null
convert ./bmp/sprite_498_back.bmp	./xpm/sprite_498_back.xpm 2>/dev/null
convert ./bmp/sprite_499_front.bmp	./xpm/sprite_499_front.xpm 2>/dev/null
convert ./bmp/sprite_499_back.bmp	./xpm/sprite_499_back.xpm 2>/dev/null
convert ./bmp/sprite_500_front.bmp	./xpm/sprite_500_front.xpm 2>/dev/null
convert ./bmp/sprite_500_back.bmp	./xpm/sprite_500_back.xpm 2>/dev/null
convert ./bmp/sprite_501_front.bmp	./xpm/sprite_501_front.xpm 2>/dev/null
convert ./bmp/sprite_501_back.bmp	./xpm/sprite_501_back.xpm 2>/dev/null
convert ./bmp/sprite_502_front.bmp	./xpm/sprite_502_front.xpm 2>/dev/null
convert ./bmp/sprite_502_back.bmp	./xpm/sprite_502_back.xpm 2>/dev/null
convert ./bmp/sprite_503_front.bmp	./xpm/sprite_503_front.xpm 2>/dev/null
convert ./bmp/sprite_503_back.bmp	./xpm/sprite_503_back.xpm 2>/dev/null
convert ./bmp/sprite_504_front.bmp	./xpm/sprite_504_front.xpm 2>/dev/null
convert ./bmp/sprite_504_back.bmp	./xpm/sprite_504_back.xpm 2>/dev/null
convert ./bmp/sprite_505_front.bmp	./xpm/sprite_505_front.xpm 2>/dev/null
convert ./bmp/sprite_505_back.bmp	./xpm/sprite_505_back.xpm 2>/dev/null
convert ./bmp/sprite_506_front.bmp	./xpm/sprite_506_front.xpm 2>/dev/null
convert ./bmp/sprite_506_back.bmp	./xpm/sprite_506_back.xpm 2>/dev/null
convert ./bmp/sprite_507_front.bmp	./xpm/sprite_507_front.xpm 2>/dev/null
convert ./bmp/sprite_507_back.bmp	./xpm/sprite_507_back.xpm 2>/dev/null
convert ./bmp/sprite_508_front.bmp	./xpm/sprite_508_front.xpm 2>/dev/null
convert ./bmp/sprite_508_back.bmp	./xpm/sprite_508_back.xpm 2>/dev/null
convert ./bmp/sprite_509_front.bmp	./xpm/sprite_509_front.xpm 2>/dev/null
convert ./bmp/sprite_509_back.bmp	./xpm/sprite_509_back.xpm 2>/dev/null
convert ./bmp/sprite_510_front.bmp	./xpm/sprite_510_front.xpm 2>/dev/null
convert ./bmp/sprite_510_back.bmp	./xpm/sprite_510_back.xpm 2>/dev/null
convert ./bmp/sprite_511_front.bmp	./xpm/sprite_511_front.xpm 2>/dev/null
convert ./bmp/sprite_511_back.bmp	./xpm/sprite_511_back.xpm 2>/dev/null
convert ./bmp/sprite_512_front.bmp	./xpm/sprite_512_front.xpm 2>/dev/null
convert ./bmp/sprite_512_back.bmp	./xpm/sprite_512_back.xpm 2>/dev/null
convert ./bmp/sprite_513_front.bmp	./xpm/sprite_513_front.xpm 2>/dev/null
convert ./bmp/sprite_513_back.bmp	./xpm/sprite_513_back.xpm 2>/dev/null
convert ./bmp/sprite_514_front.bmp	./xpm/sprite_514_front.xpm 2>/dev/null
convert ./bmp/sprite_514_back.bmp	./xpm/sprite_514_back.xpm 2>/dev/null
convert ./bmp/sprite_515_front.bmp	./xpm/sprite_515_front.xpm 2>/dev/null
convert ./bmp/sprite_515_back.bmp	./xpm/sprite_515_back.xpm 2>/dev/null
convert ./bmp/sprite_516_front.bmp	./xpm/sprite_516_front.xpm 2>/dev/null
convert ./bmp/sprite_516_back.bmp	./xpm/sprite_516_back.xpm 2>/dev/null
convert ./bmp/sprite_517_front.bmp	./xpm/sprite_517_front.xpm 2>/dev/null
convert ./bmp/sprite_517_back.bmp	./xpm/sprite_517_back.xpm 2>/dev/null
convert ./bmp/sprite_518_front.bmp	./xpm/sprite_518_front.xpm 2>/dev/null
convert ./bmp/sprite_518_back.bmp	./xpm/sprite_518_back.xpm 2>/dev/null
convert ./bmp/sprite_519_front.bmp	./xpm/sprite_519_front.xpm 2>/dev/null
convert ./bmp/sprite_519_back.bmp	./xpm/sprite_519_back.xpm 2>/dev/null
convert ./bmp/sprite_520_front.bmp	./xpm/sprite_520_front.xpm 2>/dev/null
convert ./bmp/sprite_520_back.bmp	./xpm/sprite_520_back.xpm 2>/dev/null
convert ./bmp/sprite_521_front.bmp	./xpm/sprite_521_front.xpm 2>/dev/null
convert ./bmp/sprite_521_back.bmp	./xpm/sprite_521_back.xpm 2>/dev/null
convert ./bmp/sprite_522_front.bmp	./xpm/sprite_522_front.xpm 2>/dev/null
convert ./bmp/sprite_522_back.bmp	./xpm/sprite_522_back.xpm 2>/dev/null
convert ./bmp/sprite_523_front.bmp	./xpm/sprite_523_front.xpm 2>/dev/null
convert ./bmp/sprite_523_back.bmp	./xpm/sprite_523_back.xpm 2>/dev/null
convert ./bmp/sprite_524_front.bmp	./xpm/sprite_524_front.xpm 2>/dev/null
convert ./bmp/sprite_524_back.bmp	./xpm/sprite_524_back.xpm 2>/dev/null
convert ./bmp/sprite_525_front.bmp	./xpm/sprite_525_front.xpm 2>/dev/null
convert ./bmp/sprite_525_back.bmp	./xpm/sprite_525_back.xpm 2>/dev/null
convert ./bmp/sprite_526_front.bmp	./xpm/sprite_526_front.xpm 2>/dev/null
convert ./bmp/sprite_526_back.bmp	./xpm/sprite_526_back.xpm 2>/dev/null
convert ./bmp/sprite_527_front.bmp	./xpm/sprite_527_front.xpm 2>/dev/null
convert ./bmp/sprite_527_back.bmp	./xpm/sprite_527_back.xpm 2>/dev/null
convert ./bmp/sprite_528_front.bmp	./xpm/sprite_528_front.xpm 2>/dev/null
convert ./bmp/sprite_528_back.bmp	./xpm/sprite_528_back.xpm 2>/dev/null
convert ./bmp/sprite_529_front.bmp	./xpm/sprite_529_front.xpm 2>/dev/null
convert ./bmp/sprite_529_back.bmp	./xpm/sprite_529_back.xpm 2>/dev/null
convert ./bmp/sprite_530_front.bmp	./xpm/sprite_530_front.xpm 2>/dev/null
convert ./bmp/sprite_530_back.bmp	./xpm/sprite_530_back.xpm 2>/dev/null
convert ./bmp/sprite_531_front.bmp	./xpm/sprite_531_front.xpm 2>/dev/null
convert ./bmp/sprite_531_back.bmp	./xpm/sprite_531_back.xpm 2>/dev/null
convert ./bmp/sprite_532_front.bmp	./xpm/sprite_532_front.xpm 2>/dev/null
convert ./bmp/sprite_532_back.bmp	./xpm/sprite_532_back.xpm 2>/dev/null
convert ./bmp/sprite_533_front.bmp	./xpm/sprite_533_front.xpm 2>/dev/null
convert ./bmp/sprite_533_back.bmp	./xpm/sprite_533_back.xpm 2>/dev/null
convert ./bmp/sprite_534_front.bmp	./xpm/sprite_534_front.xpm 2>/dev/null
convert ./bmp/sprite_534_back.bmp	./xpm/sprite_534_back.xpm 2>/dev/null
convert ./bmp/sprite_535_front.bmp	./xpm/sprite_535_front.xpm 2>/dev/null
convert ./bmp/sprite_535_back.bmp	./xpm/sprite_535_back.xpm 2>/dev/null
convert ./bmp/sprite_536_front.bmp	./xpm/sprite_536_front.xpm 2>/dev/null
convert ./bmp/sprite_536_back.bmp	./xpm/sprite_536_back.xpm 2>/dev/null
convert ./bmp/sprite_537_front.bmp	./xpm/sprite_537_front.xpm 2>/dev/null
convert ./bmp/sprite_537_back.bmp	./xpm/sprite_537_back.xpm 2>/dev/null
convert ./bmp/sprite_538_front.bmp	./xpm/sprite_538_front.xpm 2>/dev/null
convert ./bmp/sprite_538_back.bmp	./xpm/sprite_538_back.xpm 2>/dev/null
convert ./bmp/sprite_539_front.bmp	./xpm/sprite_539_front.xpm 2>/dev/null
convert ./bmp/sprite_539_back.bmp	./xpm/sprite_539_back.xpm 2>/dev/null
convert ./bmp/sprite_540_front.bmp	./xpm/sprite_540_front.xpm 2>/dev/null
convert ./bmp/sprite_540_back.bmp	./xpm/sprite_540_back.xpm 2>/dev/null
convert ./bmp/sprite_541_front.bmp	./xpm/sprite_541_front.xpm 2>/dev/null
convert ./bmp/sprite_541_back.bmp	./xpm/sprite_541_back.xpm 2>/dev/null
convert ./bmp/sprite_542_front.bmp	./xpm/sprite_542_front.xpm 2>/dev/null
convert ./bmp/sprite_542_back.bmp	./xpm/sprite_542_back.xpm 2>/dev/null
convert ./bmp/sprite_543_front.bmp	./xpm/sprite_543_front.xpm 2>/dev/null
convert ./bmp/sprite_543_back.bmp	./xpm/sprite_543_back.xpm 2>/dev/null
convert ./bmp/sprite_544_front.bmp	./xpm/sprite_544_front.xpm 2>/dev/null
convert ./bmp/sprite_544_back.bmp	./xpm/sprite_544_back.xpm 2>/dev/null
convert ./bmp/sprite_545_front.bmp	./xpm/sprite_545_front.xpm 2>/dev/null
convert ./bmp/sprite_545_back.bmp	./xpm/sprite_545_back.xpm 2>/dev/null
convert ./bmp/sprite_546_front.bmp	./xpm/sprite_546_front.xpm 2>/dev/null
convert ./bmp/sprite_546_back.bmp	./xpm/sprite_546_back.xpm 2>/dev/null
convert ./bmp/sprite_547_front.bmp	./xpm/sprite_547_front.xpm 2>/dev/null
convert ./bmp/sprite_547_back.bmp	./xpm/sprite_547_back.xpm 2>/dev/null
convert ./bmp/sprite_548_front.bmp	./xpm/sprite_548_front.xpm 2>/dev/null
convert ./bmp/sprite_548_back.bmp	./xpm/sprite_548_back.xpm 2>/dev/null
convert ./bmp/sprite_549_front.bmp	./xpm/sprite_549_front.xpm 2>/dev/null
convert ./bmp/sprite_549_back.bmp	./xpm/sprite_549_back.xpm 2>/dev/null
convert ./bmp/sprite_550_front.bmp	./xpm/sprite_550_front.xpm 2>/dev/null
convert ./bmp/sprite_550_back.bmp	./xpm/sprite_550_back.xpm 2>/dev/null
convert ./bmp/sprite_551_front.bmp	./xpm/sprite_551_front.xpm 2>/dev/null
convert ./bmp/sprite_551_back.bmp	./xpm/sprite_551_back.xpm 2>/dev/null
convert ./bmp/sprite_552_front.bmp	./xpm/sprite_552_front.xpm 2>/dev/null
convert ./bmp/sprite_552_back.bmp	./xpm/sprite_552_back.xpm 2>/dev/null
convert ./bmp/sprite_553_front.bmp	./xpm/sprite_553_front.xpm 2>/dev/null
convert ./bmp/sprite_553_back.bmp	./xpm/sprite_553_back.xpm 2>/dev/null
convert ./bmp/sprite_554_front.bmp	./xpm/sprite_554_front.xpm 2>/dev/null
convert ./bmp/sprite_554_back.bmp	./xpm/sprite_554_back.xpm 2>/dev/null
convert ./bmp/sprite_555_front.bmp	./xpm/sprite_555_front.xpm 2>/dev/null
convert ./bmp/sprite_555_back.bmp	./xpm/sprite_555_back.xpm 2>/dev/null
convert ./bmp/sprite_556_front.bmp	./xpm/sprite_556_front.xpm 2>/dev/null
convert ./bmp/sprite_556_back.bmp	./xpm/sprite_556_back.xpm 2>/dev/null
convert ./bmp/sprite_557_front.bmp	./xpm/sprite_557_front.xpm 2>/dev/null
convert ./bmp/sprite_557_back.bmp	./xpm/sprite_557_back.xpm 2>/dev/null
convert ./bmp/sprite_558_front.bmp	./xpm/sprite_558_front.xpm 2>/dev/null
convert ./bmp/sprite_558_back.bmp	./xpm/sprite_558_back.xpm 2>/dev/null
convert ./bmp/sprite_559_front.bmp	./xpm/sprite_559_front.xpm 2>/dev/null
convert ./bmp/sprite_559_back.bmp	./xpm/sprite_559_back.xpm 2>/dev/null
convert ./bmp/sprite_560_front.bmp	./xpm/sprite_560_front.xpm 2>/dev/null
convert ./bmp/sprite_560_back.bmp	./xpm/sprite_560_back.xpm 2>/dev/null
convert ./bmp/sprite_561_front.bmp	./xpm/sprite_561_front.xpm 2>/dev/null
convert ./bmp/sprite_561_back.bmp	./xpm/sprite_561_back.xpm 2>/dev/null
convert ./bmp/sprite_562_front.bmp	./xpm/sprite_562_front.xpm 2>/dev/null
convert ./bmp/sprite_562_back.bmp	./xpm/sprite_562_back.xpm 2>/dev/null
convert ./bmp/sprite_563_front.bmp	./xpm/sprite_563_front.xpm 2>/dev/null
convert ./bmp/sprite_563_back.bmp	./xpm/sprite_563_back.xpm 2>/dev/null
convert ./bmp/sprite_564_front.bmp	./xpm/sprite_564_front.xpm 2>/dev/null
convert ./bmp/sprite_564_back.bmp	./xpm/sprite_564_back.xpm 2>/dev/null
convert ./bmp/sprite_565_front.bmp	./xpm/sprite_565_front.xpm 2>/dev/null
convert ./bmp/sprite_565_back.bmp	./xpm/sprite_565_back.xpm 2>/dev/null
convert ./bmp/sprite_566_front.bmp	./xpm/sprite_566_front.xpm 2>/dev/null
convert ./bmp/sprite_566_back.bmp	./xpm/sprite_566_back.xpm 2>/dev/null
convert ./bmp/sprite_567_front.bmp	./xpm/sprite_567_front.xpm 2>/dev/null
convert ./bmp/sprite_567_back.bmp	./xpm/sprite_567_back.xpm 2>/dev/null
convert ./bmp/sprite_568_front.bmp	./xpm/sprite_568_front.xpm 2>/dev/null
convert ./bmp/sprite_568_back.bmp	./xpm/sprite_568_back.xpm 2>/dev/null
convert ./bmp/sprite_569_front.bmp	./xpm/sprite_569_front.xpm 2>/dev/null
convert ./bmp/sprite_569_back.bmp	./xpm/sprite_569_back.xpm 2>/dev/null
convert ./bmp/sprite_570_front.bmp	./xpm/sprite_570_front.xpm 2>/dev/null
convert ./bmp/sprite_570_back.bmp	./xpm/sprite_570_back.xpm 2>/dev/null
convert ./bmp/sprite_571_front.bmp	./xpm/sprite_571_front.xpm 2>/dev/null
convert ./bmp/sprite_571_back.bmp	./xpm/sprite_571_back.xpm 2>/dev/null
convert ./bmp/sprite_572_front.bmp	./xpm/sprite_572_front.xpm 2>/dev/null
convert ./bmp/sprite_572_back.bmp	./xpm/sprite_572_back.xpm 2>/dev/null
convert ./bmp/sprite_573_front.bmp	./xpm/sprite_573_front.xpm 2>/dev/null
convert ./bmp/sprite_573_back.bmp	./xpm/sprite_573_back.xpm 2>/dev/null
convert ./bmp/sprite_574_front.bmp	./xpm/sprite_574_front.xpm 2>/dev/null
convert ./bmp/sprite_574_back.bmp	./xpm/sprite_574_back.xpm 2>/dev/null
convert ./bmp/sprite_575_front.bmp	./xpm/sprite_575_front.xpm 2>/dev/null
convert ./bmp/sprite_575_back.bmp	./xpm/sprite_575_back.xpm 2>/dev/null
convert ./bmp/sprite_576_front.bmp	./xpm/sprite_576_front.xpm 2>/dev/null
convert ./bmp/sprite_576_back.bmp	./xpm/sprite_576_back.xpm 2>/dev/null
convert ./bmp/sprite_577_front.bmp	./xpm/sprite_577_front.xpm 2>/dev/null
convert ./bmp/sprite_577_back.bmp	./xpm/sprite_577_back.xpm 2>/dev/null
convert ./bmp/sprite_578_front.bmp	./xpm/sprite_578_front.xpm 2>/dev/null
convert ./bmp/sprite_578_back.bmp	./xpm/sprite_578_back.xpm 2>/dev/null
convert ./bmp/sprite_579_front.bmp	./xpm/sprite_579_front.xpm 2>/dev/null
convert ./bmp/sprite_579_back.bmp	./xpm/sprite_579_back.xpm 2>/dev/null
convert ./bmp/sprite_580_front.bmp	./xpm/sprite_580_front.xpm 2>/dev/null
convert ./bmp/sprite_580_back.bmp	./xpm/sprite_580_back.xpm 2>/dev/null
convert ./bmp/sprite_581_front.bmp	./xpm/sprite_581_front.xpm 2>/dev/null
convert ./bmp/sprite_581_back.bmp	./xpm/sprite_581_back.xpm 2>/dev/null
convert ./bmp/sprite_582_front.bmp	./xpm/sprite_582_front.xpm 2>/dev/null
convert ./bmp/sprite_582_back.bmp	./xpm/sprite_582_back.xpm 2>/dev/null
convert ./bmp/sprite_583_front.bmp	./xpm/sprite_583_front.xpm 2>/dev/null
convert ./bmp/sprite_583_back.bmp	./xpm/sprite_583_back.xpm 2>/dev/null
convert ./bmp/sprite_584_front.bmp	./xpm/sprite_584_front.xpm 2>/dev/null
convert ./bmp/sprite_584_back.bmp	./xpm/sprite_584_back.xpm 2>/dev/null
convert ./bmp/sprite_585_front.bmp	./xpm/sprite_585_front.xpm 2>/dev/null
convert ./bmp/sprite_585_back.bmp	./xpm/sprite_585_back.xpm 2>/dev/null
convert ./bmp/sprite_586_front.bmp	./xpm/sprite_586_front.xpm 2>/dev/null
convert ./bmp/sprite_586_back.bmp	./xpm/sprite_586_back.xpm 2>/dev/null
convert ./bmp/sprite_587_front.bmp	./xpm/sprite_587_front.xpm 2>/dev/null
convert ./bmp/sprite_587_back.bmp	./xpm/sprite_587_back.xpm 2>/dev/null
convert ./bmp/sprite_588_front.bmp	./xpm/sprite_588_front.xpm 2>/dev/null
convert ./bmp/sprite_588_back.bmp	./xpm/sprite_588_back.xpm 2>/dev/null
convert ./bmp/sprite_589_front.bmp	./xpm/sprite_589_front.xpm 2>/dev/null
convert ./bmp/sprite_589_back.bmp	./xpm/sprite_589_back.xpm 2>/dev/null
convert ./bmp/sprite_590_front.bmp	./xpm/sprite_590_front.xpm 2>/dev/null
convert ./bmp/sprite_590_back.bmp	./xpm/sprite_590_back.xpm 2>/dev/null
convert ./bmp/sprite_591_front.bmp	./xpm/sprite_591_front.xpm 2>/dev/null
convert ./bmp/sprite_591_back.bmp	./xpm/sprite_591_back.xpm 2>/dev/null
convert ./bmp/sprite_592_front.bmp	./xpm/sprite_592_front.xpm 2>/dev/null
convert ./bmp/sprite_592_back.bmp	./xpm/sprite_592_back.xpm 2>/dev/null
convert ./bmp/sprite_593_front.bmp	./xpm/sprite_593_front.xpm 2>/dev/null
convert ./bmp/sprite_593_back.bmp	./xpm/sprite_593_back.xpm 2>/dev/null
convert ./bmp/sprite_594_front.bmp	./xpm/sprite_594_front.xpm 2>/dev/null
convert ./bmp/sprite_594_back.bmp	./xpm/sprite_594_back.xpm 2>/dev/null
convert ./bmp/sprite_595_front.bmp	./xpm/sprite_595_front.xpm 2>/dev/null
convert ./bmp/sprite_595_back.bmp	./xpm/sprite_595_back.xpm 2>/dev/null
convert ./bmp/sprite_596_front.bmp	./xpm/sprite_596_front.xpm 2>/dev/null
convert ./bmp/sprite_596_back.bmp	./xpm/sprite_596_back.xpm 2>/dev/null
convert ./bmp/sprite_597_front.bmp	./xpm/sprite_597_front.xpm 2>/dev/null
convert ./bmp/sprite_597_back.bmp	./xpm/sprite_597_back.xpm 2>/dev/null
convert ./bmp/sprite_598_front.bmp	./xpm/sprite_598_front.xpm 2>/dev/null
convert ./bmp/sprite_598_back.bmp	./xpm/sprite_598_back.xpm 2>/dev/null
convert ./bmp/sprite_599_front.bmp	./xpm/sprite_599_front.xpm 2>/dev/null
convert ./bmp/sprite_599_back.bmp	./xpm/sprite_599_back.xpm 2>/dev/null
convert ./bmp/sprite_600_front.bmp	./xpm/sprite_600_front.xpm 2>/dev/null
convert ./bmp/sprite_600_back.bmp	./xpm/sprite_600_back.xpm 2>/dev/null
convert ./bmp/sprite_601_front.bmp	./xpm/sprite_601_front.xpm 2>/dev/null
convert ./bmp/sprite_601_back.bmp	./xpm/sprite_601_back.xpm 2>/dev/null
convert ./bmp/sprite_602_front.bmp	./xpm/sprite_602_front.xpm 2>/dev/null
convert ./bmp/sprite_602_back.bmp	./xpm/sprite_602_back.xpm 2>/dev/null
convert ./bmp/sprite_603_front.bmp	./xpm/sprite_603_front.xpm 2>/dev/null
convert ./bmp/sprite_603_back.bmp	./xpm/sprite_603_back.xpm 2>/dev/null
convert ./bmp/sprite_604_front.bmp	./xpm/sprite_604_front.xpm 2>/dev/null
convert ./bmp/sprite_604_back.bmp	./xpm/sprite_604_back.xpm 2>/dev/null
convert ./bmp/sprite_605_front.bmp	./xpm/sprite_605_front.xpm 2>/dev/null
convert ./bmp/sprite_605_back.bmp	./xpm/sprite_605_back.xpm 2>/dev/null
convert ./bmp/sprite_606_front.bmp	./xpm/sprite_606_front.xpm 2>/dev/null
convert ./bmp/sprite_606_back.bmp	./xpm/sprite_606_back.xpm 2>/dev/null
convert ./bmp/sprite_607_front.bmp	./xpm/sprite_607_front.xpm 2>/dev/null
convert ./bmp/sprite_607_back.bmp	./xpm/sprite_607_back.xpm 2>/dev/null
convert ./bmp/sprite_608_front.bmp	./xpm/sprite_608_front.xpm 2>/dev/null
convert ./bmp/sprite_608_back.bmp	./xpm/sprite_608_back.xpm 2>/dev/null
convert ./bmp/sprite_609_front.bmp	./xpm/sprite_609_front.xpm 2>/dev/null
convert ./bmp/sprite_609_back.bmp	./xpm/sprite_609_back.xpm 2>/dev/null
convert ./bmp/sprite_610_front.bmp	./xpm/sprite_610_front.xpm 2>/dev/null
convert ./bmp/sprite_610_back.bmp	./xpm/sprite_610_back.xpm 2>/dev/null
convert ./bmp/sprite_611_front.bmp	./xpm/sprite_611_front.xpm 2>/dev/null
convert ./bmp/sprite_611_back.bmp	./xpm/sprite_611_back.xpm 2>/dev/null
convert ./bmp/sprite_612_front.bmp	./xpm/sprite_612_front.xpm 2>/dev/null
convert ./bmp/sprite_612_back.bmp	./xpm/sprite_612_back.xpm 2>/dev/null
convert ./bmp/sprite_613_front.bmp	./xpm/sprite_613_front.xpm 2>/dev/null
convert ./bmp/sprite_613_back.bmp	./xpm/sprite_613_back.xpm 2>/dev/null
convert ./bmp/sprite_614_front.bmp	./xpm/sprite_614_front.xpm 2>/dev/null
convert ./bmp/sprite_614_back.bmp	./xpm/sprite_614_back.xpm 2>/dev/null
convert ./bmp/sprite_615_front.bmp	./xpm/sprite_615_front.xpm 2>/dev/null
convert ./bmp/sprite_615_back.bmp	./xpm/sprite_615_back.xpm 2>/dev/null
convert ./bmp/sprite_616_front.bmp	./xpm/sprite_616_front.xpm 2>/dev/null
convert ./bmp/sprite_616_back.bmp	./xpm/sprite_616_back.xpm 2>/dev/null
convert ./bmp/sprite_617_front.bmp	./xpm/sprite_617_front.xpm 2>/dev/null
convert ./bmp/sprite_617_back.bmp	./xpm/sprite_617_back.xpm 2>/dev/null
convert ./bmp/sprite_618_front.bmp	./xpm/sprite_618_front.xpm 2>/dev/null
convert ./bmp/sprite_618_back.bmp	./xpm/sprite_618_back.xpm 2>/dev/null
convert ./bmp/sprite_619_front.bmp	./xpm/sprite_619_front.xpm 2>/dev/null
convert ./bmp/sprite_619_back.bmp	./xpm/sprite_619_back.xpm 2>/dev/null
convert ./bmp/sprite_620_front.bmp	./xpm/sprite_620_front.xpm 2>/dev/null
convert ./bmp/sprite_620_back.bmp	./xpm/sprite_620_back.xpm 2>/dev/null
convert ./bmp/sprite_621_front.bmp	./xpm/sprite_621_front.xpm 2>/dev/null
convert ./bmp/sprite_621_back.bmp	./xpm/sprite_621_back.xpm 2>/dev/null
convert ./bmp/sprite_622_front.bmp	./xpm/sprite_622_front.xpm 2>/dev/null
convert ./bmp/sprite_622_back.bmp	./xpm/sprite_622_back.xpm 2>/dev/null
convert ./bmp/sprite_623_front.bmp	./xpm/sprite_623_front.xpm 2>/dev/null
convert ./bmp/sprite_623_back.bmp	./xpm/sprite_623_back.xpm 2>/dev/null
convert ./bmp/sprite_624_front.bmp	./xpm/sprite_624_front.xpm 2>/dev/null
convert ./bmp/sprite_624_back.bmp	./xpm/sprite_624_back.xpm 2>/dev/null
convert ./bmp/sprite_625_front.bmp	./xpm/sprite_625_front.xpm 2>/dev/null
convert ./bmp/sprite_625_back.bmp	./xpm/sprite_625_back.xpm 2>/dev/null
convert ./bmp/sprite_626_front.bmp	./xpm/sprite_626_front.xpm 2>/dev/null
convert ./bmp/sprite_626_back.bmp	./xpm/sprite_626_back.xpm 2>/dev/null
convert ./bmp/sprite_627_front.bmp	./xpm/sprite_627_front.xpm 2>/dev/null
convert ./bmp/sprite_627_back.bmp	./xpm/sprite_627_back.xpm 2>/dev/null
convert ./bmp/sprite_628_front.bmp	./xpm/sprite_628_front.xpm 2>/dev/null
convert ./bmp/sprite_628_back.bmp	./xpm/sprite_628_back.xpm 2>/dev/null
convert ./bmp/sprite_629_front.bmp	./xpm/sprite_629_front.xpm 2>/dev/null
convert ./bmp/sprite_629_back.bmp	./xpm/sprite_629_back.xpm 2>/dev/null
convert ./bmp/sprite_630_front.bmp	./xpm/sprite_630_front.xpm 2>/dev/null
convert ./bmp/sprite_630_back.bmp	./xpm/sprite_630_back.xpm 2>/dev/null
convert ./bmp/sprite_631_front.bmp	./xpm/sprite_631_front.xpm 2>/dev/null
convert ./bmp/sprite_631_back.bmp	./xpm/sprite_631_back.xpm 2>/dev/null
convert ./bmp/sprite_632_front.bmp	./xpm/sprite_632_front.xpm 2>/dev/null
convert ./bmp/sprite_632_back.bmp	./xpm/sprite_632_back.xpm 2>/dev/null
convert ./bmp/sprite_633_front.bmp	./xpm/sprite_633_front.xpm 2>/dev/null
convert ./bmp/sprite_633_back.bmp	./xpm/sprite_633_back.xpm 2>/dev/null
convert ./bmp/sprite_634_front.bmp	./xpm/sprite_634_front.xpm 2>/dev/null
convert ./bmp/sprite_634_back.bmp	./xpm/sprite_634_back.xpm 2>/dev/null
convert ./bmp/sprite_635_front.bmp	./xpm/sprite_635_front.xpm 2>/dev/null
convert ./bmp/sprite_635_back.bmp	./xpm/sprite_635_back.xpm 2>/dev/null
convert ./bmp/sprite_636_front.bmp	./xpm/sprite_636_front.xpm 2>/dev/null
convert ./bmp/sprite_636_back.bmp	./xpm/sprite_636_back.xpm 2>/dev/null
convert ./bmp/sprite_637_front.bmp	./xpm/sprite_637_front.xpm 2>/dev/null
convert ./bmp/sprite_637_back.bmp	./xpm/sprite_637_back.xpm 2>/dev/null
convert ./bmp/sprite_638_front.bmp	./xpm/sprite_638_front.xpm 2>/dev/null
convert ./bmp/sprite_638_back.bmp	./xpm/sprite_638_back.xpm 2>/dev/null
convert ./bmp/sprite_639_front.bmp	./xpm/sprite_639_front.xpm 2>/dev/null
convert ./bmp/sprite_639_back.bmp	./xpm/sprite_639_back.xpm 2>/dev/null
convert ./bmp/sprite_640_front.bmp	./xpm/sprite_640_front.xpm 2>/dev/null
convert ./bmp/sprite_640_back.bmp	./xpm/sprite_640_back.xpm 2>/dev/null
convert ./bmp/sprite_641_front.bmp	./xpm/sprite_641_front.xpm 2>/dev/null
convert ./bmp/sprite_641_back.bmp	./xpm/sprite_641_back.xpm 2>/dev/null
convert ./bmp/sprite_642_front.bmp	./xpm/sprite_642_front.xpm 2>/dev/null
convert ./bmp/sprite_642_back.bmp	./xpm/sprite_642_back.xpm 2>/dev/null
convert ./bmp/sprite_643_front.bmp	./xpm/sprite_643_front.xpm 2>/dev/null
convert ./bmp/sprite_643_back.bmp	./xpm/sprite_643_back.xpm 2>/dev/null
convert ./bmp/sprite_644_front.bmp	./xpm/sprite_644_front.xpm 2>/dev/null
convert ./bmp/sprite_644_back.bmp	./xpm/sprite_644_back.xpm 2>/dev/null
convert ./bmp/sprite_645_front.bmp	./xpm/sprite_645_front.xpm 2>/dev/null
convert ./bmp/sprite_645_back.bmp	./xpm/sprite_645_back.xpm 2>/dev/null
convert ./bmp/sprite_646_front.bmp	./xpm/sprite_646_front.xpm 2>/dev/null
convert ./bmp/sprite_646_back.bmp	./xpm/sprite_646_back.xpm 2>/dev/null
convert ./bmp/sprite_647_front.bmp	./xpm/sprite_647_front.xpm 2>/dev/null
convert ./bmp/sprite_647_back.bmp	./xpm/sprite_647_back.xpm 2>/dev/null
convert ./bmp/sprite_648_front.bmp	./xpm/sprite_648_front.xpm 2>/dev/null
convert ./bmp/sprite_648_back.bmp	./xpm/sprite_648_back.xpm 2>/dev/null
convert ./bmp/sprite_649_front.bmp	./xpm/sprite_649_front.xpm 2>/dev/null
convert ./bmp/sprite_649_back.bmp	./xpm/sprite_649_back.xpm 2>/dev/null